package org.skyve.impl.tools.javadoc.doctor;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import org.junit.jupiter.api.Test;
import org.skyve.impl.metadata.model.document.field.Text;

class DoctorFragmentsTest {

	private static String captureHTML(HTMLWriter writer) {
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		try (PrintStream printStream = new PrintStream(out)) {
			writer.write(printStream);
		}
		return out.toString();
	}

	@FunctionalInterface
	private interface HTMLWriter {
		void write(PrintStream out);
	}

	@Test
	void docHeadWritesTitleAndStylesheet() {
		DocHead head = new DocHead("Skyve Docs");
		head.setStyleSheet("styles.css");
		head.setTitle("Skyve Docs Updated");

		String html = captureHTML(head::generateHTML);
		assertEquals("styles.css", head.getStyleSheet());
		assertEquals("Skyve Docs Updated", head.getTitle());
		assertTrue(html.contains("<title>Skyve Docs Updated</title>"));
		assertTrue(html.contains("href=\"styles.css\""));
		assertTrue(html.startsWith("<html>"));
	}

	@Test
	void docFooterWritesClosingMarkup() {
		DocFooter footer = new DocFooter("footerId");
		footer.setTitle("Generated by Skyve");
		footer.setId("footerUpdated");

		String html = captureHTML(footer::generateHTML);
		assertEquals("footerUpdated", footer.getId());
		assertEquals("Generated by Skyve", footer.getTitle());
		assertTrue(html.contains("id=\"footerUpdated\""));
		assertTrue(html.contains("Generated by Skyve"));
		assertTrue(html.contains("</html>"));
	}

	@Test
	void docListRendersOrderedAndUnorderedLists() {
		DocList unordered = new DocList(false);
		unordered.getItems().add("one");
		unordered.getItems().add("two");

		DocList ordered = new DocList(true);
		ordered.getItems().add("alpha");

		assertEquals("<ul><li>one</li><li>two</li></ul>", unordered.toHTML());
		assertEquals("<ol><li>alpha</li></ol>", ordered.toHTML());
	}

	@Test
	void docHeaderIncludesOptionalImages() {
		DocHeader header = new DocHeader("Report");
		header.setTitle("Updated Report");
		header.setLogoLocation("logo.png");
		header.setRibbonBarLocation("ribbon.png");

		String html = header.toHTML();
		assertEquals("Updated Report", header.getTitle());
		assertEquals("logo.png", header.getLogoLocation());
		assertEquals("ribbon.png", header.getRibbonBarLocation());
		assertTrue(html.contains("logo.png"));
		assertTrue(html.contains("ribbon.png"));
		assertTrue(html.contains("Updated Report"));
	}

	@Test
	void docSectionSupportsHeadingVariants() {
		DocSection section = new DocSection("section-1");
		section.setSectionTitle("Overview");
		section.getHtmlContent().add("<p>Body</p>");
		section.setId("section-2");

		assertEquals("section-2", section.getId());
		assertEquals("Overview", section.getSectionTitle());
		assertEquals(DocSection.SectionType.Section, section.getSectionType());
		assertTrue(section.toHTML().startsWith("<h3>Overview</h3>"));

		section.setSectionType(DocSection.SectionType.Chapter);
		assertTrue(section.toHTML().startsWith("<h1>Overview</h1>"));

		section.setSectionType(DocSection.SectionType.SubChapter);
		assertTrue(section.toHTML().startsWith("<h2>Overview</h2>"));

		section.setSectionType(DocSection.SectionType.SubTitle);
		assertTrue(section.toHTML().startsWith("<h4>Overview</h4>"));
	}

	@Test
	void docTableUsesListFallbackForSingleVisibleColumn() {
		DocTable table = new DocTable("table-1");
		table.setTitle("Items");
		table.setId("table-1-updated");
		table.setHeaderValues("Name", "Description");
		table.setRowValues("Alpha", null);
		table.setRowValues("Beta", "");

		assertEquals("table-1-updated", table.getId());
		assertEquals("Items", table.getTitle());
		assertEquals("Name", table.getHeaders()[0]);
		String html = table.toHTML(true);
		assertTrue(html.contains("<ul>"));
		assertTrue(html.contains("<li>Alpha</li>"));
		assertTrue(html.contains("<li>Beta</li>"));
	}

	@Test
	void docTableRendersTableAndOmitsEmptyColumns() {
		DocTable table = new DocTable("table-2");
		table.setTitle("Data");
		table.setHeaders(new String[] {"First", "Skip", "Last"});
		table.setRowValues("A", null, "Z");
		table.setRowValues("B", "", "Y");

		assertEquals("Data", table.getTitle());
		assertEquals(3, table.getHeaders().length);
		assertEquals(0, table.getHtmlContent().size());
		String html = table.toHTML(false);
		assertTrue(html.contains("<table cellspacing=\"1\" class=\"dataTable\">"));
		assertTrue(html.contains("<th>First</th>"));
		assertTrue(html.contains("<th>Last</th>"));
		assertTrue(!html.contains("<th>Skip</th>"));
		assertTrue(html.contains("<td>A</td>"));
		assertTrue(html.contains("<td>Z</td>"));
	}

	@Test
	void textFieldSupportsLengthSetter() {
		Text text = new Text();
		text.setName("summary");
		text.setDisplayName("Summary");
		text.setDescription("Summary text");
		text.setLength(123);

		assertEquals("summary", text.getName());
		assertEquals("Summary", text.getDisplayName());
		assertEquals("Summary text", text.getDescription());
		assertEquals(123, text.getLength());
		assertNotNull(text.getImplementingType());
	}
}