isc.DataSource.create({
    operationBindings:[
        {
            operationId:"dsFromSQL",
            operationType:"custom"
        },
        {
            operationId:"dsFromTable",
            operationType:"custom"
        },
        {
            operationId:"dsFromConfig",
            operationType:"custom"
        }
    ],
    allowAdvancedCriteria:true,
    ID:"DataSourceStore",
    fields:[
        {
            name:"ID",
            validators:[
            ],
            primaryKey:true
        },
        {
            name:"version",
            validators:[
            ]
        },
        {
            length:50000,
            name:"dsXML",
            type:"text",
            validators:[
            ]
        },
        {
            hidden:true,
            name:"config",
            validators:[
            ]
        },
        {
            hidden:true,
            name:"dbName",
            validators:[
            ]
        },
        {
            hidden:true,
            name:"tableName",
            validators:[
            ]
        },
        {
            hidden:true,
            name:"schema",
            validators:[
            ]
        },
        {
            hidden:true,
            name:"sql",
            validators:[
            ]
        },
        {
            name:"ds",
            hidden:true,
            type:"DataSource",
            validators:[
            ]
        }
    ]
})
