isc.DataSource.create({
    operationBindings:[
        {
            operationType:"fetch"
        }
    ],
    allowAdvancedCriteria:true,
    ID:"DBListDS",
    dropExtraFields:false,
    fields:[
        {
            name:"name",
            validators:[
            ],
            primaryKey:true
        },
        {
            name:"type",
            validators:[
            ]
        },
        {
            name:"version",
            validators:[
            ]
        },
        {
            name:"driverVersion",
            validators:[
            ]
        },
        {
            name:"status",
            validators:[
            ]
        }
    ]
})
