isc.DataSource.create({
    operationBindings:[
        {
            operationType:"fetch"
        }
    ],
    allowAdvancedCriteria:true,
    ID:"DBSchema",
    fields:[
        {
            name:"name",
            validators:[
            ]
        },
        {
            name:"itemType",
            validators:[
            ]
        },
        {
            name:"type",
            validators:[
            ]
        },
        {
            name:"length",
            type:"integer",
            validators:[
            ]
        },
        {
            name:"primaryKey",
            type:"boolean",
            validators:[
            ]
        },
        {
            name:"path",
            hidden:true,
            validators:[
            ],
            primaryKey:true
        },
        {
            name:"parentID",
            hidden:true,
            foreignKey:"DBSchema.path",
            validators:[
            ]
        }
    ]
})
