isc.DataSource.create({
    operationBindings:[
        {
            operationId:"start",
            operationType:"custom"
        },
        {
            operationId:"shutdown",
            operationType:"custom"
        },
        {
            operationId:"standby",
            operationType:"custom"
        },
        {
            operationId:"doit",
            operationType:"custom"
        }
    ],
    allowAdvancedCriteria:true,
    ID:"QuartzScheduler",
    fields:[
        {
            name:"name",
            type:"text",
            validators:[
            ],
            canEdit:false
        },
        {
            name:"state",
            valueMap:{
                "0":"Shutdown",
                "1":"Standby",
                "2":"Started"
            },
            type:"intEnum",
            validators:[
            ],
            canEdit:false
        }
    ]
})
