isc.DataSource.create({
    allowAdvancedCriteria:true,
    ID:"QuartzTriggers",
    fields:[
        {
            name:"jobGroup",
            showIf:"false",
            type:"string",
            required:true,
            validators:[
            ]
        },
        {
            name:"jobName",
            showIf:"false",
            type:"string",
            required:true,
            validators:[
            ]
        },
        {
            name:"group",
            type:"string",
            required:true,
            validators:[
            ],
            primaryKey:true
        },
        {
            name:"name",
            type:"string",
            required:true,
            validators:[
            ],
            primaryKey:true
        },
        {
            name:"description",
            type:"string",
            validators:[
            ]
        },
        {
            name:"dataMap",
            showIf:"false",
            type:"Object",
            validators:[
            ]
        },
        {
            name:"startTime",
            type:"date",
            validators:[
            ]
        },
        {
            name:"endTime",
            type:"date",
            validators:[
            ]
        },
        {
            name:"cronExpression",
            type:"text",
            required:true,
            validators:[
            ]
        },
        {
            name:"timeZone",
            type:"text",
            validators:[
            ]
        },
        {
            name:"volatility",
            type:"boolean",
            defaultValue:"false",
            validators:[
            ]
        },
        {
            name:"misfireInstruction",
            valueMap:{
                "0":"MISFIRE_INSTRUCTION_SMART_POLICY",
                "1":"MISFIRE_INSTRUCTION_FIRE_ONCE_NOW",
                "2":"MISFIRE_INSTRUCTION_DO_NOTHING"
            },
            type:"intEnum",
            defaultValue:"0",
            validators:[
            ]
        },
        {
            name:"state",
            valueMap:{
                "0":"Normal",
                "1":"Paused",
                "2":"Complete",
                "3":"Error",
                "4":"Blocked",
                "-1":"None"
            },
            type:"intEnum",
            validators:[
            ],
            canEdit:false
        }
    ]
})
