window.SKYVE||(window.SKYVE={});
SKYVE.Util=function(){const z=function(w,d){null!==d&&(w.readyState?w.onreadystatechange=function(){if("loaded"===w.readyState||"complete"===w.readyState)w.onreadystatechange=null,d()}:w.onload=d);const g=document.getElementsByTagName("HEAD")[0];g&&g.appendChild(w)};return{customer:null,v:null,googleMapsV3ApiKey:null,ckEditorConfigFileUrl:null,mapCentre:null,mapZoom:1,CONTEXT_URL:`${window.location}`.substring(0,`${window.location}`.lastIndexOf("/")+1),allowedReportFormats:null,unsanitiseBinding:function(w){return w.replace(/_(\d*)_/g,
"[$1]").replace(/_/g,".")},loadJS:function(w,d){const g=document.createElement("SCRIPT");g.type="text/javascript";g.src=w;z(g,d)},loadCSS:function(w,d){const g=document.createElement("LINK");g.type="text/css";g.rel="stylesheet";g.href=w;z(g,d)},geoLocate:function(w){navigator.geolocation&&($(function(){PrimeFaces.cw("Growl","growl",{id:"growl",widgetVar:"growl",msgs:[{summary:"GeoLocating",detail:"Please wait...",severity:"info"}]})}),navigator.geolocation.getCurrentPosition(function(d){$(function(){PrimeFaces.cw("Growl",
"growl",{id:"growl",widgetVar:"growl",msgs:[{summary:"GeoLocating",detail:"Done",severity:"info"}]})});w(`POINT (${d.coords.longitude} ${d.coords.latitude})`)},function(d){$(function(){PrimeFaces.cw("Growl","growl",{id:"growl",widgetVar:"growl",msgs:[{summary:"GeoLocating",detail:d.message,severity:"warn"}]})})},{enableHighAccuracy:!0}))},setTouchCookie:function(){let w=!1;if("maxTouchPoints"in navigator)w=0<navigator.maxTouchPoints;else if("msMaxTouchPoints"in navigator)w=0<navigator.msMaxTouchPoints;
else{const d=window.matchMedia&&matchMedia("(pointer:coarse)");d&&"(pointer:coarse)"===d.media?w=!!d.matches:"orientation"in window&&(w=!0)}document.cookie=`touch=${w?1:0}; path=/`},passwordStrength:{0:"Worst",1:"Bad",2:"Weak",3:"Good",4:"Strong"},progressBarPower:{0:"1%",1:"25%",2:"50%",3:"75%",4:"100%"},progressBarColour:{0:"#D73F40",1:"#DC6551",2:"#F2B84F",3:"#BDE952",4:"#3ba62f"}}}();
SKYVE.GMap=function(){let z=null;const w=function(d){switch(d){case "point":d=[google.maps.drawing.OverlayType.MARKER];break;case "line":d=[google.maps.drawing.OverlayType.POLYLINE];break;case "polygon":d=[google.maps.drawing.OverlayType.POLYGON,google.maps.drawing.OverlayType.RECTANGLE];break;case "pointAndLine":d=[google.maps.drawing.OverlayType.MARKER,google.maps.drawing.OverlayType.POLYLINE];break;case "pointAndPolygon":d=[google.maps.drawing.OverlayType.MARKER,google.maps.drawing.OverlayType.POLYGON,
google.maps.drawing.OverlayType.RECTANGLE];break;case "lineAndPolygon":d=[google.maps.drawing.OverlayType.POLYLINE,google.maps.drawing.OverlayType.POLYGON,google.maps.drawing.OverlayType.RECTANGLE];break;default:d=[google.maps.drawing.OverlayType.MARKER,google.maps.drawing.OverlayType.POLYLINE,google.maps.drawing.OverlayType.POLYGON,google.maps.drawing.OverlayType.RECTANGLE]}return d};return{scatter:function(d,g,x,v){z||=new Wkt.Wkt;var B=g.items;if(B){if(v)for(var q in d._objects){if(Object.prototype.hasOwnProperty.call(d._objects,
q)){var b=!1;for(let h=0,t=B.length;h<t;h++)if(B[h].bizId===q){b=!0;break}if(!b){b=d._objects[q];for(let h=0,t=b.overlays.length;h<t;h++)b.overlays[h].setMap(null),b.overlays[h]=null;delete b.overlays;delete d._objects[q]}}}else for(b in d._objects)if(Object.prototype.hasOwnProperty.call(d._objects,b)){q=d._objects[b];for(let h=0,t=q.overlays.length;h<t;h++)q.overlays[h].setMap(null),q.overlays[h]=null;delete q.overlays;delete d._objects[b]}for(let h=0,t=B.length;h<t;h++){q=B[h];if(b=d._objects[q.bizId]){if(v=
b.overlays.length===q.features.length)for(let m=0,p=b.overlays.length;m<p;m++)if(b.overlays[m].geometry!==q.features[m].geometry){v=!1;break}if(!v){for(let m=0,p=b.overlays.length;m<p;m++)b.overlays[m].setMap(null),b.overlays[m]=null;delete b.overlays;delete d._objects[bizId];b=null}}if(!b){b={overlays:[]};for(let m=0,p=q.features.length;m<p;m++){v=q.features[m];try{z.read(v.geometry)}catch(u){alert(`${v.geometry} is invalid WKT.`);continue}var e={editable:v.editable};v.strokeColour&&(e.strokeColor=
v.strokeColour);v.fillColour&&(e.fillColor=v.fillColour);v.fillOpacity&&(e.fillOpacity=v.fillOpacity);v.iconRelativeFilePath&&(e.icon={url:`${SKYVE.Util.CONTEXT_URL}resources?_n=${v.iconRelativeFilePath}&_doc=${g._doc}`},v.iconAnchorX&&v.iconAnchorY&&(e.icon.anchor=new google.maps.Point(v.iconAnchorX,v.iconAnchorY),e.icon.origin=new google.maps.Point(0,0)));e=z.toObject(e);b.overlays.push(e);e.setMap(d.webmap);v.zoomable&&(e.bizId=q.bizId,e.geometry=v.geometry,e.fromTimestamp=q.fromTimestamp,e.toTimestamp=
q.toTimestamp,e.mod=q.moduleName,e.doc=q.documentName,e.infoMarkup=q.infoMarkup,google.maps.event.addListener(e,"click",function(u){d.click(this,u)}))}d._objects[q.bizId]=b}}if(x){g=new google.maps.LatLngBounds;x=!1;for(const h in d._objects)if(Object.prototype.hasOwnProperty.call(d._objects,h)){x=!0;B=d._objects[h].overlays;for(let t=0,m=B.length;t<m;t++)if(q=B[t],q.getPath){q=q.getPath();for(let p=0,u=q.getLength();p<u;p++)g.extend(q.getAt(p))}else q.getPosition&&g.extend(q.getPosition())}x&&(g.getNorthEast().equals(g.getSouthWest())?
(15>d.webmap.getZoom()&&d.webmap.setZoom(15),void 0!==overlay.getPosition&&"function"===typeof overlay.getPosition&&d.webmap.setCenter(g.getNorthEast())):d.webmap.fitBounds(g))}}},centre:function(){z||=new Wkt.Wkt;let d=null;if(SKYVE.Util.mapCentre)try{z.read(SKYVE.Util.mapCentre);const g=z.components[0];d=new google.maps.LatLng(g.y,g.x)}catch(g){console.log(`${SKYVE.Util.mapCentre} is malformed WKT Point format`),SKYVE.Util.mapCentre=null,d=new google.maps.LatLng(0,0)}else d=new google.maps.LatLng(0,
0);return d},scatterValue:function(d,g){z||=new Wkt.Wkt;if(g){try{z.read(g)}catch(v){if("WKTError"===v.name){alert("The WKT string is invalid.");return}}g=z.toObject(d.webmap.defaults);"polygon"!==z.type&&"linestring"!==z.type&&g.setEditable&&g.setEditable(!1);if(Wkt.isArray(g))for(var x in g)Object.prototype.hasOwnProperty.call(g,x)&&!Wkt.isArray(g[x])&&(g[x].setMap(d.webmap),d._overlays.push(g[x]));else g.setMap(d.webmap),d._overlays.push(g);if(void 0!==g.getBounds&&"function"===typeof g.getBounds)d.webmap.fitBounds(g.getBounds());
else if(void 0!==g.getPath&&"function"===typeof g.getPath){x=new google.maps.LatLngBounds;g=g.getPath();for(let v=0,B=g.getLength();v<B;v++)x.extend(g.getAt(v));d.webmap.fitBounds(x)}else 15>d.webmap.getZoom()&&d.webmap.setZoom(15),void 0!==g.getPosition&&"function"===typeof g.getPosition&&d.webmap.setCenter(g.getPosition())}},clear:function(d){for(let g=0,x=d._overlays.length;g<x;g++)d._overlays[g].setMap(null);d._overlays.length=0},drawingTools:function(d){z||=new Wkt.Wkt;d.webmap.drawingManager=
new google.maps.drawing.DrawingManager({drawingControlOptions:{position:google.maps.ControlPosition.LEFT_BOTTOM,drawingModes:w(d.drawingTools)}});d.webmap.drawingManager.setMap(d.webmap);google.maps.event.addListener(d.webmap.drawingManager,"overlaycomplete",function(g){SKYVE.GMap.clear(d);this.setDrawingMode(null);d._overlays.push(g.overlay);z.fromObject(g.overlay);g=z.write();d.setFieldValue(g)})},geoLocator:function(d){if(navigator.geolocation){const g=document.createElement("DIV");Object.assign(g.style,
{backgroundColor:"#fff",border:"2px solid #fff",borderRadius:"3px",boxShadow:"0 2px 6px rgba(0,0,0,.3)",cursor:"pointer",margin:"10px",padding:"5px",textAlign:"center"});g.title="Click to set your current position from your GPS";g.innerHTML='<i class="fa-solid fa-location-crosshairs"></i>';g.index=1;g.addEventListener("click",function(){navigator.geolocation.getCurrentPosition(function(x){SKYVE.GMap.clear(d);d.webmap.drawingManager.setDrawingMode(null);x={lat:x.coords.latitude,lng:x.coords.longitude};
const v=new google.maps.Marker({position:x,map:d.webmap});d._overlays.push(v);d.setFieldValue(`POINT (${x.lng} ${x.lat})`);d.webmap.setZoom(15);d.webmap.setCenter(x)},function(x){alert(x.message)},{enableHighAccuracy:!0})});d.webmap.geolocator=g;d.webmap.controls[google.maps.ControlPosition.LEFT].push(g)}},setDisabled:function(d,g){d.webmap&&(d.webmap.drawingManager&&d.webmap.drawingManager.setOptions({drawingControl:!g}),d.webmap.geolocator&&(d.webmap.geolocator.style.display=g?"none":"block"))},
refreshControls:function(d){const g=document.createElement("DIV");Object.assign(g.style,{backgroundColor:"#fff",border:"2px solid #fff",borderRadius:"3px",boxShadow:"0 2px 6px rgba(0,0,0,.3)",cursor:"pointer",margin:"10px",padding:"5px",textAlign:"center"});g.title="Click to set the refresh rate of the map";g.innerHTML=`
						        <input type="number" min="0" max="500" step="1" value="${d.refreshTime}" size="3" />
						        <input type="checkbox" ${d._refreshRequired?"checked":""}><label>Refresh</label>
						    `;g.index=1;g.children[0].addEventListener("change",function(){d.refreshTime=Number(this.value);d._refreshRequired&&(d._intervalId&&clearInterval(d._intervalId),d._intervalId=setInterval(d.rerender.bind(d),1E3*d.refreshTime))});g.children[1].addEventListener("click",function(){d._refreshRequired=this.checked;d._intervalId&&(clearInterval(d._intervalId),d._intervalId=null);d._refreshRequired&&(d.rerender(),d._intervalId=setInterval(d.rerender.bind(d),1E3*d.refreshTime))});d.webmap.controls[google.maps.ControlPosition.LEFT_BOTTOM].push(g)}}}();
SKYVE.Leaflet=function(){function z(b){function e(l){l=n.substring(r).match(l);if(!l)return null;r+=l[0].length;return l[0]}function h(){e(/^\s*/)}function t(){h();let l=0;const y=[],C=[y];let D=y,E;for(;E=e(/^(\()/)||e(/^(\))/)||e(/^(,)/)||e(q);){if("("===E)C.push(D),D=[],C[C.length-1].push(D),l++;else if(")"===E){if(0===D.length)return null;D=C.pop();if(!D)return null;l--;if(0===l)break}else if(","===E)D=[],C[C.length-1].push(D);else{if(E.split(/\s/g).some(isNaN))return null;Array.prototype.push.apply(D,
E.split(/\s/g).map(parseFloat))}h()}return 0!==l?null:y}function m(){const l=[];let y=[],C;for(;C=e(q)||e(/^(,)/);)","===C?(l.push(y),y=[]):C.split(/\s/g).some(isNaN)||(y||=[],Array.prototype.push.apply(y,C.split(/\s/g).map(parseFloat))),h();if(y)l.push(y);else return null;return l.length?l:null}function p(){if(!e(/^(point(\sz)?)/i))return null;h();if(!e(/^(\()/))return null;const l=m();if(!l)return null;h();return e(/^(\))/)?{type:"Point",coordinates:l[0]}:null}function u(){if(!e(/^(multipoint)/i))return null;
h();n=`MULTIPOINT (${n.substring(n.indexOf("(")+1,n.length-1).replace(/\(/g,"").replace(/\)/g,"")})`;const l=t();if(!l)return null;h();return{type:"MultiPoint",coordinates:l}}function A(){if(!e(/^(multilinestring)/i))return null;h();const l=t();if(!l)return null;h();return{type:"MultiLineString",coordinates:l}}function a(){if(!e(/^(linestring(\sz)?)/i))return null;h();if(!e(/^(\()/))return null;const l=m();return l&&e(/^(\))/)?{type:"LineString",coordinates:l}:null}function c(){const l=[];let y;if(!e(/^(geometrycollection)/i))return null;
h();if(!e(/^(\()/))return null;for(;y=f();)l.push(y),h(),e(/^(,)/),h();return e(/^(\))/)?{type:"GeometryCollection",geometries:l}:null}function f(){var l;(l=p()||a())||(e(/^(polygon(\sz)?)/i)?(h(),l=(l=t())?{type:"Polygon",coordinates:l}:null):l=null);(l=l||u()||A())||(e(/^(multipolygon)/i)?(h(),l=(l=t())?{type:"MultiPolygon",coordinates:l}:null):l=null);return l||c()}b=b.split(";");let n=b.pop();const k=(b.shift()||"").split("=").pop();let r=0;return function(l){l&&k.match(/\d+/)&&(l.crs={type:"name",
properties:{name:`urn:ogc:def:crs:EPSG::${k}`}});return l}(f())}function w(b){function e(p){return p.join(" ")}function h(p){return p.map(e).join(", ")}function t(p){return p.map(h).map(m).join(", ")}function m(p){return`(${p})`}"Feature"===b.type&&(b=b.geometry);switch(b.type){case "Point":return`POINT (${e(b.coordinates)})`;case "LineString":return`LINESTRING (${h(b.coordinates)})`;case "Polygon":return`POLYGON (${t(b.coordinates)})`;case "MultiPoint":return`MULTIPOINT (${h(b.coordinates)})`;case "MultiPolygon":return`MULTIPOLYGON (${b.coordinates.map(t).map(m).join(", ")})`;
case "MultiLineString":return`MULTILINESTRING (${t(b.coordinates)})`;case "GeometryCollection":return`GEOMETRYCOLLECTION (${b.geometries.map(w).join(", ")})`;default:throw Error("stringify requires a valid GeoJSON Feature or geometry object as input");}}function d(b,e,h){if(h&&(h=b.webmap.getMaxZoom(),isFinite(h)?(b._markerClusterGroup&&b._markerClusterGroup._map===b.webmap||(b._markerClusterGroup=L.markerClusterGroup({showCoverageOnHover:!0,zoomToBoundsOnClick:!0,spiderfyOnMaxZoom:!0,removeOutsideVisibleBounds:!0,
maxClusterRadius:40,spiderLegPolylineOptions:{weight:1.5,color:"#333",opacity:.5}}),b.webmap.addLayer(b._markerClusterGroup)),h=b._markerClusterGroup):h=null,h)){e._skyveClustered=!0;h.addLayer(e);return}b.webmap.addLayer(e)}function g(b,e){e._skyveClustered&&b._markerClusterGroup?b._markerClusterGroup.removeLayer(e):b.webmap.removeLayer(e)}function x(b){return b.zoomData?b.zoomData.geometry:b.getLayers&&(b=b.getLayers(),b.length&&b[0].zoomData)?b[0].zoomData.geometry:null}function v(b){return b.getBounds?
b.getBounds():b.getLatLng?(b=b.getLatLng(),L.latLngBounds(b,b)):null}const B=/[-+]?([0-9]*\.[0-9]+|[0-9]+)([eE][-+]?[0-9]+)?/,q=new RegExp("^"+B.source+"(\\s"+B.source+"){1,}");return{scatter:function(b,e,h,t){var m=e.items;if(m){if(t)for(var p in b._objects){if(Object.prototype.hasOwnProperty.call(b._objects,p)){var u=!1;for(let A=0,a=m.length;A<a;A++)if(m[A].bizId===p){u=!0;break}if(!u){u=b._objects[p];for(let A=0,a=u.overlays.length;A<a;A++)g(b,u.overlays[A]),u.overlays[A]=null;delete u.overlays;
delete b._objects[p]}}}else for(u in b._objects)if(Object.prototype.hasOwnProperty.call(b._objects,u)){p=b._objects[u];for(let A=0,a=p.overlays.length;A<a;A++)g(b,p.overlays[A]),p.overlays[A]=null;delete p.overlays;delete b._objects[u]}for(let A=0,a=m.length;A<a;A++){const c=m[A];if(p=b._objects[c.bizId]){if(u=p.overlays.length===c.features.length)for(let f=0,n=p.overlays.length;f<n;f++)if(x(p.overlays[f])!==c.features[f].geometry){u=!1;break}if(!u){for(let f=0,n=p.overlays.length;f<n;f++)g(b,p.overlays[f]),
p.overlays[f]=null;delete p.overlays;delete b._objects[c.bizId];p=null}}if(!p){p={overlays:[]};for(let f=0,n=c.features.length;f<n;f++){const k=c.features[f];u=z(k.geometry);u.properties={editable:k.editable};k.strokeColour&&(u.properties.color=k.strokeColour);k.fillColour&&(u.properties.fillColor=k.fillColour);k.fillOpacity&&(u.properties.fillOpacity=k.fillOpacity);k.iconRelativeFilePath&&(t={iconUrl:`${SKYVE.Util.CONTEXT_URL}resources?_n=${k.iconRelativeFilePath}&_doc=${e._doc}`},k.iconAnchorX&&
k.iconAnchorY&&(t.iconAnchor=[k.iconAnchorX,k.iconAnchorY]),u.properties.icon=t);t=u&&("Point"===u.type||"MultiPoint"===u.type)&&u.properties&&!u.properties.editable&&L.markerClusterGroup;u=L.geoJson(u,{pointToLayer(r,l){const y=r.properties;delete r.properties;y.icon&&(y.icon=L.icon(y.icon));return L.marker(l,y)},style:function(r){const l=r.geometry.properties;delete r.geometry.properties;return l},onEachFeature:function(r,l){k.zoomable&&(l.zoomData={bizId:c.bizId,geometry:k.geometry,fromTimestamp:c.fromTimestamp,
toTimestamp:c.toTimestamp,mod:c.moduleName,doc:c.documentName,infoMarkup:c.infoMarkup},l.bindPopup(function(y){return b.click(y)}))}});p.overlays.push(u);d(b,u,t)}b._objects[c.bizId]=p}}if(h){e=L.latLngBounds();h=!1;for(const A in b._objects)if(Object.prototype.hasOwnProperty.call(b._objects,A)){h=!0;m=b._objects[A].overlays;for(let a=0,c=m.length;a<c;a++)(p=v(m[a]))&&e.extend(p)}h&&b.webmap.fitBounds(e,{maxZoom:15})}}},centre:function(){let b=[0,0];if(SKYVE.Util.mapCentre)try{const e=z(SKYVE.Util.mapCentre);
b=[e.coordinates[1],e.coordinates[0]]}catch(e){console.log(`${SKYVE.Util.mapCentre} is malformed WKT Point format`),SKYVE.Util.mapCentre=null}return b},scatterValue:function(b,e){if(e){var h=null;try{h=L.geoJson(z(e))}catch(t){console.log(`The WKT string ${e} is invalid.`);return}h.addTo(b.webmap);b._overlays.push(h);b.webmap.fitBounds(h.getBounds(),{maxZoom:15})}},clear:function(b){for(let e=0,h=b._overlays.length;e<h;e++)b.webmap.removeLayer(b._overlays[e]);b._overlays.length=0},drawingTools:function(b){const e=
b.drawingTools;L.EditControl=L.Control.extend({options:{position:"topright"},onAdd:function(h){const t=L.DomUtil.create("div","leaflet-control leaflet-bar");if(!e||"point"===e||"pointAndLine"===e||"pointAndPolygon"===e){var m=L.DomUtil.create("a","",t);m.href="#";m.title="Create a new marker";m.innerHTML='<i class="fa-solid fa-location-dot"></i>';L.DomEvent.on(m,"click",L.DomEvent.stop).on(m,"click",function(){window.LAYER=b.webmap.editTools.startMarker.call(h.editTools)},this)}e&&"line"!==e&&"pointAndLine"!==
e&&"lineAndPolygon"!==e||(m=L.DomUtil.create("a","",t),m.href="#",m.title="Create a new line",m.innerHTML='<i class="fa-solid fa-diagram-project"></i>',L.DomEvent.on(m,"click",L.DomEvent.stop).on(m,"click",function(){window.LAYER=b.webmap.editTools.startPolyline.call(h.editTools)},this));e&&"polygon"!==e&&"pointAndPolygon"!==e&&"lineAndPolygon"!==e||(m=L.DomUtil.create("a","",t),m.href="#",m.title="Create a new rectangle",m.innerHTML='<i class="fa-solid fa-vector-square"></i>',L.DomEvent.on(m,"click",
L.DomEvent.stop).on(m,"click",function(){window.LAYER=b.webmap.editTools.startRectangle.call(h.editTools)},this),m=L.DomUtil.create("a","",t),m.href="#",m.title="Create a new polygon",m.innerHTML='<i class="fa-solid fa-draw-polygon"></i>',L.DomEvent.on(m,"click",L.DomEvent.stop).on(m,"click",function(){window.LAYER=b.webmap.editTools.startPolygon.call(h.editTools)},this));return t}});b.webmap.editControl=new L.EditControl;b.webmap.addControl(b.webmap.editControl);b.webmap.on("editable:drawing:commit",
function(h){SKYVE.Leaflet.clear(b);h.layer.toggleEdit();b._overlays.push(h.layer);b.setFieldValue(w(h.layer.toGeoJSON(12)))})},geoLocator:function(b){navigator.geolocation&&(L.GeoControl=L.Control.extend({options:{position:"bottomleft"},onAdd:function(e){e=L.DomUtil.create("div","leaflet-control leaflet-bar");const h=L.DomUtil.create("a","",e);h.href="#";h.title="Click to set your current position from your GPS";h.innerHTML='<i class="fa-solid fa-location-crosshairs"></i>';L.DomEvent.on(h,"click",
L.DomEvent.stop).on(h,"click",function(){b.webmap.editTools.drawing()&&b.webmap.editTools.commitDrawing();navigator.geolocation.getCurrentPosition(function(t){SKYVE.Leaflet.clear(b);const m=[t.coords.latitude,t.coords.longitude],p=L.marker(m);p.addTo(b.webmap);b._overlays.push(p);b.setFieldValue(`POINT (${t.coords.longitude} ${t.coords.latitude})`);b.webmap.setZoom(15);b.webmap.panTo(m)},function(t){alert(t.message)},{enableHighAccuracy:!0})},this);return e}}),b.webmap.geoControl=new L.GeoControl,
b.webmap.addControl(b.webmap.geoControl))},setDisabled:function(b,e){b.webmap&&(b.webmap.editControl&&(b.webmap.editControl.getContainer().style.display=e?"none":"block"),b.webmap.geoControl&&(b.webmap.geoControl.getContainer().style.display=e?"none":"block"))},refreshControls:function(b){L.GeoControl=L.Control.extend({options:{position:"bottomleft"},onAdd:function(e){e=L.DomUtil.create("div","leaflet-control");e.innerHTML=`
		                <input type="number" min="0" max="500" step="1" value="${b.refreshTime}" size="3" />
		                <input type="checkbox" ${b._refreshRequired?"checked":""}><label>Refresh</label>
		            `;e.children[0].addEventListener("change",function(){b.refreshTime=Number(this.value);b._refreshRequired&&(b._intervalId&&clearInterval(b._intervalId),b._intervalId=setInterval(b.rerender.bind(b),1E3*b.refreshTime))});e.children[1].addEventListener("click",function(){b._refreshRequired=this.checked;b._intervalId&&(clearInterval(b._intervalId),b._intervalId=null);b._refreshRequired&&(b.rerender(),b._intervalId=setInterval(b.rerender.bind(b),1E3*b.refreshTime))});return e}});b.webmap.addControl(new L.GeoControl)}}}();SKYVE.PF=function(){var z=!1,w=function(){var a=sessionStorage.sessionHistory;return a=a?JSON.parse(a):[]},d={},g={},x={},v=function(a){return a.replace(/_(\d*)_/g,"[$1]").replace(/_/g,".")},B=function(a,c,f){a=a?a+"_"+c+f:"_"+c+f;return'[id="'+a+'"],[id$=":'+a+'"]'},q=function(a,c,f,n){var k=[f],r=f.lastIndexOf("_");-1<r&&r<f.length-1&&(r=f.substring(r+1),"_"===f.charAt(0)&&k.push("_"+r),k.push(r));f=a.$();r=0;for(var l=k.length;r<l;r++)if(f=a.$(B(c,k[r],n)),0<f.length)return f;if(c)for(c=0,r=k.length;c<
r&&!(f=a.$(B(null,k[c],n)),0<f.length);c++);return f},b=function(a,c,f,n,k){q(a,c,f,n).val(k).attr("value",k).trigger("change")},e=function(a,c,f,n,k){a=a.$(B(c,f,n));0<a.length&&a.val(k).attr("value",k).trigger("change")},h=function(a,c,f){q(a,c,f,"_link").attr("href","javascript:void(0)").text("<Empty>").attr("onclick","return false").off("click.skyveContentClear").on("click.skyveContentClear",function(){return!1})},t=function(a,c,f,n){q(a,c,f,"_video").each(function(){var k=a.$(this),r=k.children("video");
0<r.length?r.attr("src",n):k.append('<video controls preload="metadata" style="width:100%;height:100%;object-fit:contain" src="'+n+'"></video>')})},m=function(a,c,f){q(a,c,f,"_video").each(function(){a.$(this).children("video").remove()})},p=function(a,c,f,n){q(a,c,f,"_link").toggleClass("skyveContentHidden",!!n&&"link"!==n);var k=q(a,c,f,"_image"),r="image"===n;k.toggleClass("skyveContentHidden",!r);k.parent().toggleClass("skyveContentHidden",!r);a=q(a,c,f,"_video");n="video"===n;a.toggleClass("skyveContentHidden",
!n);a.parent().toggleClass("skyveContentHidden",!n)},u=function(a,c,f,n){c=c?a.$(".skyveContentMarkupAction-"+c+"_"+f):a.$();a=0<c.length?c:a.$(".skyveContentMarkupAction-"+f);a.toggleClass("skyveContentHidden","image"!==n)},A=function(a,c,f){return(a?top.PF(a+"_"+c+f):null)||top.PF(c+f)};return{getById:function(a){return $(PrimeFaces.escapeClientId(a))},getByIdEndsWith:function(a){return $('[id$="'+a+'"]')},contentOverlayOnShow:function(a,c){var f;(f=(f=RegExp("[?&]_n=([^&]*)").exec(c))?decodeURIComponent(f[1].replace(/\+/g,
" ")):null)&&(d[f]=a);SKYVE.PF.getById(a+"_overlayiframe").attr("src",c)},contentOverlayOnHide:function(a){SKYVE.PF.getById(a+"_overlayiframe").attr("src","")},afterContentUpload:function(a,c,f,n,k,r){var l=d[a];b(top,l,a,"_hidden",c);k&&r&&e(top,l,r,"_hidden",k);c="content?_n="+c+"&_doc="+f+"&_b="+v(a);q(top,l,a,"_link").off("click.skyveContentClear").attr("href",c).text(n).attr("onclick","return true");q(top,l,a,"_image").attr("src",c);t(top,l,a,c);r&&p(top,l,a,k);u(top,l,a,k);(n=A(l,a,"Overlay"))&&
n.hide();delete d[a]},clearContentImage:function(a,c,f){b(top,c,a,"_hidden","");f&&e(top,c,f,"_hidden","");h(top,c,a);q(top,c,a,"_image").attr("src","images/blank.gif");m(top,c,a);f&&p(top,c,a,"");u(top,c,a,"")},clearContentLink:function(a,c,f){b(top,c,a,"_hidden","");f&&e(top,c,f,"_hidden","");h(top,c,a);m(top,c,a);f&&p(top,c,a,"");u(top,c,a,"")},clearContent:function(a,c,f){SKYVE.PF.clearContentLink(a,c,f);q(top,c,a,"_image").attr("src","images/blank.gif")},contentMarkupOnShow:function(a,c,f,n){g[c]=
a;n&&(x[c]=n);c=f+("&_id="+q(window,a,c,"_hidden").val());SKYVE.PF.getById(a+"_markupiframe").attr("src",c)},contentMarkupOnHide:function(a){SKYVE.PF.getById(a+"_markupiframe").attr("src","")},afterMarkupApply:function(a,c,f,n){var k=g[a];b(top,k,a,"_hidden",c);var r=x[a];r&&e(top,k,r,"_hidden","image");c="content?_n="+c+"&_doc="+f+"&_b="+v(a);q(top,k,a,"_link").off("click.skyveContentClear").attr("href",c).text(n).attr("onclick","return true");q(top,k,a,"_image").attr("src",c);r&&p(top,k,a,"image");
u(top,k,a,"image");(n=A(k,a,"Markup"))&&n.hide();delete g[a];delete x[a]},tabChange:function(a,c,f,n){sessionStorage["tab_"+a+"_"+c+"_"+f]=n;SKYVE.BizMap&&SKYVE.BizMap.resizeAll();SKYVE.BizMapPicker&&SKYVE.BizMapPicker.resizeAll()},getTextElement:function(a){return SKYVE.PF.getById(a)},getTextValue:function(a){return SKYVE.PF.getTextElement(a).val()},setTextValue:function(a,c){SKYVE.PF.getTextElement(a).val(c)},getPasswordElement:function(a){return SKYVE.PF.getById(a+"password")},getPasswordValue:function(a){return SKYVE.PF.getPasswordElement(a).val()},
setPasswordValue:function(a,c){SKYVE.PF.getPasswordElement(a).val(c)},getComboElement:function(a){return SKYVE.PF.getById(a)},getLookupElement:function(a){return SKYVE.PF.getById(a)},getLookupValue:function(a){return SKYVE.PF.getById(a+"_hinput").val()},setLookupValue:function(a,c){SKYVE.PF.getById(a+"_hinput").val(c)},getLookupDescription:function(a){return SKYVE.PF.getById(a+"_input").val()},setLookupDescription:function(a,c){SKYVE.PF.getById(a+"_input").val(c)},getCheckboxElement:function(a){return SKYVE.PF.getById(a)},
getCheckboxValue:function(a){var c=SKYVE.PF.getById(a+"_input").val();return"0"==c?null:"1"==c?!0:"2"==c?!1:SKYVE.PF.getById(a+"_input").is(":checked")},setCheckboxValue:function(a,c){SKYVE.PF.getById(a+"_input").prop("checked",c);a=SKYVE.PF.getById(a).find(".ui-chkbox-box");var f=a.find(".ui-chkbox-icon");c?(a.addClass("ui-state-active"),f.addClass("ui-icon ui-icon-check")):(a.removeClass("ui-state-active"),f.removeClass("ui-icon ui-icon-check"))},establishHistory:function(){var a=w();if(0==a.length){var c=
window.location.href;if(c.match(/.*[\?|&]a=e.*/)||c.match(/.*[\?|&]a=e&.*/)){var f=document.referrer;f&&""!=f&&f!=c||(f=SKYVE.Util.CONTEXT_URL);a.push(f);sessionStorage.sessionHistory=JSON.stringify(a)}}},startHistory:function(a){sessionStorage.sessionHistory="[]";window.location.assign(a)},pushHistory:function(a){var c=w();c.push(window.location.href);sessionStorage.sessionHistory=JSON.stringify(c);a&&window.location.assign(a)},popHistory:function(a){var c=w();if(0<c.length){var f=c.pop();sessionStorage.sessionHistory=
JSON.stringify(c);a&&window.location.assign(f)}},saveHistory:function(a,c,f){for(var n=w(),k=!1,r=0;r<n.length;r++){for(var l=n[r],y=l.split(/\?|&/),C="m="+a,D="d="+c,E=!1,H=!1,I=!1,J=!1,G=0;G<y.length;G++){var F=y[G];"a=e"==F?E=!0:F==C?H=!0:F==D?I=!0:F.startsWith("i=")&&(J=!0)}E&&H&&I&&J&&(l+="&i="+f,n[r]=l,k=!0)}k&&(sessionStorage.sessionHistory=JSON.stringify(n));window.history&&history.replaceState&&(l=window.location.href+"&i="+f,history.replaceState({},"",l))},toggleFilters:function(a){a=$('[id$="'+
a+'"]');if(null!=a){var c=function(){var f=$(this);f.hasClass("hiddenFilter")?f.removeClass("hiddenFilter"):f.addClass("hiddenFilter")};a.find(".ui-filter-column").each(c);a.find(".ui-column-customfilter").each(c)}},onPushMessage:function(a){for(var c=[],f=0,n=a.length;f<n;f++){var k=a[f];if("g"==k.type)c.push({severity:k.severity,summary:k.message});else if("m"==k.type)PrimeFaces.showMessageInDialog({severity:k.severity,summary:"",detail:k.message,escape:!1});else if("r"==k.type)pushRerender();else if("j"==
k.type)window[k.method](k.argument)}0<c.length&&PrimeFaces.cw("Growl","pushGrowl",{id:"pushGrowl",widgetVar:"pushGrowl",life:6E3,sticky:!1,msgs:c})},gmap:function(a){if(z)setTimeout(function(){SKYVE.PF.gmap(a)},100);else{if(window.google&&window.google.maps&&window.SKYVE.BizMapPicker)return a.queryName||a.modelName?SKYVE.BizMap.create(a):SKYVE.BizMapPicker.create(a);z=!0;SKYVE.Util.loadJS("wicket/wicket.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("wicket/wicket-gmap3.js?v="+SKYVE.Util.v,function(){var c=
"https://maps.googleapis.com/maps/api/js?v=3&libraries=drawing";SKYVE.Util.googleMapsV3ApiKey&&(c+="&key="+SKYVE.Util.googleMapsV3ApiKey);SKYVE.Util.loadJS(c,function(){SKYVE.Util.loadJS("skyve/prime/skyve-gmap-min.js?v="+SKYVE.Util.v,function(){z=!1;return a.queryName||a.modelName?SKYVE.BizMap.create(a):SKYVE.BizMapPicker.create(a)})})})})}},leaflet:function(a){if(z)setTimeout(function(){SKYVE.PF.leaflet(a)},100);else{if(window.L&&window.SKYVE.BizMapPicker)return a.queryName||a.modelName?SKYVE.BizMap.create(a):
SKYVE.BizMapPicker.create(a);z=!0;SKYVE.Util.loadCSS("leaflet/leaflet.css?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/leaflet.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/Path.Drag.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/Leaflet.Editable.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadCSS("leaflet/MarkerCluster.css?v="+SKYVE.Util.v,function(){SKYVE.Util.loadCSS("leaflet/MarkerCluster.Default.css?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/leaflet.markercluster.js?v="+
SKYVE.Util.v,function(){SKYVE.Util.loadCSS("leaflet/leaflet.fullscreen.css?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/Leaflet.fullscreen.min.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("skyve/prime/skyve-leaflet-min.js?v="+SKYVE.Util.v,function(){z=!1;return a.queryName||a.modelName?SKYVE.BizMap.create(a):SKYVE.BizMapPicker.create(a)})})})})})})})})})})}},chartExtender:function(){this.cfg.config.options||(this.cfg.config.options={});this.cfg.config.options.responsive=!0;this.cfg.config.options.maintainAspectRatio=
!1},sidebar:function(a,c,f,n,k){$(function(){var r=$(window),l=$("head");$("body");var y=$("#"+a);y.children(".inner");0==$("#sidebarStyle"+k).length&&$('<style id="sidebarStyle'+k+'">.sidebar'+k+"{background-color:white;font-size:0.9em;position:relative;width:"+c+";flex-grow:0;flex-shrink:0;transition:margin-right 0.5s ease,box-shadow 0.5s ease;}.sidebar"+k+" .toggle{text-decoration:none;transition:right 0.5s ease;-webkit-tap-highlight-color:rgba(255,255,255,0);border:0;display:none;position:absolute;top:calc(50% - 3.75em);right:calc("+
n+"px - 3em);width:4em;height:7.5em;line-height:6.25em;text-align:center;z-index:10000;}.sidebar"+k+" .toggle:before{font-family:FontAwesome;font-size:1.1rem;font-style:normal;font-weight:normal;text-transform:none !important;content:'>';height:inherit;right:0;line-height:inherit;position:absolute;text-indent:0;top:0;width:inherit;color:#7f888f;margin-right:1.5em;margin-top:-0.5em;z-index:1;}.sidebar"+k+" .toggle:after{background:rgba(222,225,226,0.75);border-radius:0.375em;content:'';height:3em;right:2em;position:absolute;top:1em;width:3em;}.sidebar"+
k+".inactive{margin-right:-"+n+"px;}.sidebar"+k+".inactive .toggle:before{content:'<';}@media screen and (max-width:"+f+"px){.sidebar"+k+"{box-shadow:0 0 5em 0 rgba(0,0,0,0.175);position:fixed;top:0;right:0;width:"+n+"px;height:100%;z-index:10000;}.sidebar"+k+".inactive{box-shadow:none;}.sidebar"+k+">.inner{position:absolute;top:0;right:0;width:100%;height:100%;overflow-x:hidden;overflow-y:auto;-webkit-overflow-scrolling:touch;}.sidebar"+k+" .toggle{display:flex;}}</style>").appendTo(l);r.on("resize",
function(){r.width()<=f?y.addClass("inactive"):y.removeClass("inactive")});r.trigger("resize");$('<a href="#'+a+'" class="toggle"></a>').appendTo(y).on("click",function(C){C.preventDefault();C.stopPropagation();y.toggleClass("inactive")});window.setTimeout(function(){y.show()},100)})}}}();
//# sourceMappingURL=skyve-min.js.map