window.SKYVE||(window.SKYVE={});
SKYVE.Util=function(){const y=function(d,m){null!==m&&(d.readyState?d.onreadystatechange=function(){if("loaded"===d.readyState||"complete"===d.readyState)d.onreadystatechange=null,m()}:d.onload=m);const p=document.getElementsByTagName("HEAD")[0];p&&p.appendChild(d)},H=function(d){try{return!!(d&&d.location&&d.document&&d.location.origin===window.location.origin)}catch(m){return!1}},f=function(d){try{d.focus&&d.focus()}catch(m){}},k=function(d){try{return d.location.reload(),f(d),!0}catch(m){return!1}},
w=function(d,m){try{return d.location.href=m,f(d),!0}catch(p){return!1}};return{customer:null,v:null,googleMapsV3ApiKey:null,ckEditorConfigFileUrl:null,mapCentre:null,mapZoom:1,CONTEXT_URL:`${window.location}`.substring(0,`${window.location}`.lastIndexOf("/")+1),allowedReportFormats:null,unsanitiseBinding:function(d){return d.replace(/_(\d*)_/g,"[$1]").replace(/_/g,".")},retryFromErrorPage:function(d){const m=document.createElement("a");m.href=d;d=m.href;try{var p=(new URL(d,window.location.href)).origin===
window.location.origin}catch(c){p=!1}return p?window.top&&window.top!==window?H(window.top)&&k(window.top)||w(window.top,d)?!1:!0:window.opener&&!window.opener.closed&&H(window.opener)&&k(window.opener)?!1:!w(window,d):!0},findOwnerWindow:function(d){let m=window.parent;for(;m&&m!==window;)try{if(d(m))return m;if(!m.parent||m.parent===m)break;m=m.parent}catch(p){break}return null},findSmartClientWindow:function(){return SKYVE.Util.findOwnerWindow(function(d){return!(!d.isc||!d.isc.WindowStack)})},
findPrimeFacesWindow:function(){return SKYVE.Util.findOwnerWindow(function(d){return!(!d.SKYVE||!d.SKYVE.PF)})},findSkyveWindow:function(){return SKYVE.Util.findOwnerWindow(function(d){return!!(d.isc&&d.isc.WindowStack||d.SKYVE&&d.SKYVE.PF)})},loadJS:function(d,m){const p=document.createElement("SCRIPT");p.type="text/javascript";p.src=d;y(p,m)},loadCSS:function(d,m){const p=document.createElement("LINK");p.type="text/css";p.rel="stylesheet";p.href=d;y(p,m)},geoLocate:function(d){navigator.geolocation&&
($(function(){PrimeFaces.cw("Growl","growl",{id:"growl",widgetVar:"growl",msgs:[{summary:"GeoLocating",detail:"Please wait...",severity:"info"}]})}),navigator.geolocation.getCurrentPosition(function(m){$(function(){PrimeFaces.cw("Growl","growl",{id:"growl",widgetVar:"growl",msgs:[{summary:"GeoLocating",detail:"Done",severity:"info"}]})});d(`POINT (${m.coords.longitude} ${m.coords.latitude})`)},function(m){$(function(){PrimeFaces.cw("Growl","growl",{id:"growl",widgetVar:"growl",msgs:[{summary:"GeoLocating",
detail:m.message,severity:"warn"}]})})},{enableHighAccuracy:!0}))},setTouchCookie:function(){let d=!1;if("maxTouchPoints"in navigator)d=0<navigator.maxTouchPoints;else if("msMaxTouchPoints"in navigator)d=0<navigator.msMaxTouchPoints;else{const m=window.matchMedia&&matchMedia("(pointer:coarse)");m&&"(pointer:coarse)"===m.media?d=!!m.matches:"orientation"in window&&(d=!0)}document.cookie=`touch=${d?1:0}; path=/`},passwordStrength:{0:"Worst",1:"Bad",2:"Weak",3:"Good",4:"Strong"},progressBarPower:{0:"1%",
1:"25%",2:"50%",3:"75%",4:"100%"},progressBarColour:{0:"#D73F40",1:"#DC6551",2:"#F2B84F",3:"#BDE952",4:"#3ba62f"}}}();
SKYVE.GMap=function(){let y=null;const H=function(f){switch(f){case "point":f=[google.maps.drawing.OverlayType.MARKER];break;case "line":f=[google.maps.drawing.OverlayType.POLYLINE];break;case "polygon":f=[google.maps.drawing.OverlayType.POLYGON,google.maps.drawing.OverlayType.RECTANGLE];break;case "pointAndLine":f=[google.maps.drawing.OverlayType.MARKER,google.maps.drawing.OverlayType.POLYLINE];break;case "pointAndPolygon":f=[google.maps.drawing.OverlayType.MARKER,google.maps.drawing.OverlayType.POLYGON,
google.maps.drawing.OverlayType.RECTANGLE];break;case "lineAndPolygon":f=[google.maps.drawing.OverlayType.POLYLINE,google.maps.drawing.OverlayType.POLYGON,google.maps.drawing.OverlayType.RECTANGLE];break;default:f=[google.maps.drawing.OverlayType.MARKER,google.maps.drawing.OverlayType.POLYLINE,google.maps.drawing.OverlayType.POLYGON,google.maps.drawing.OverlayType.RECTANGLE]}return f};return{scatter:function(f,k,w,d){y||=new Wkt.Wkt;var m=k.items;if(m){if(d)for(var p in f._objects){if(Object.prototype.hasOwnProperty.call(f._objects,
p)){var c=!1;for(let l=0,v=m.length;l<v;l++)if(m[l].bizId===p){c=!0;break}if(!c){c=f._objects[p];for(let l=0,v=c.overlays.length;l<v;l++)c.overlays[l].setMap(null),c.overlays[l]=null;delete c.overlays;delete f._objects[p]}}}else for(c in f._objects)if(Object.prototype.hasOwnProperty.call(f._objects,c)){p=f._objects[c];for(let l=0,v=p.overlays.length;l<v;l++)p.overlays[l].setMap(null),p.overlays[l]=null;delete p.overlays;delete f._objects[c]}for(let l=0,v=m.length;l<v;l++){p=m[l];if(c=f._objects[p.bizId]){if(d=
c.overlays.length===p.features.length)for(let q=0,t=c.overlays.length;q<t;q++)if(c.overlays[q].geometry!==p.features[q].geometry){d=!1;break}if(!d){for(let q=0,t=c.overlays.length;q<t;q++)c.overlays[q].setMap(null),c.overlays[q]=null;delete c.overlays;delete f._objects[bizId];c=null}}if(!c){c={overlays:[]};for(let q=0,t=p.features.length;q<t;q++){d=p.features[q];try{y.read(d.geometry)}catch(x){alert(`${d.geometry} is invalid WKT.`);continue}var g={editable:d.editable};d.strokeColour&&(g.strokeColor=
d.strokeColour);d.fillColour&&(g.fillColor=d.fillColour);d.fillOpacity&&(g.fillOpacity=d.fillOpacity);d.iconRelativeFilePath&&(g.icon={url:`${SKYVE.Util.CONTEXT_URL}resources?_n=${d.iconRelativeFilePath}&_doc=${k._doc}`},d.iconAnchorX&&d.iconAnchorY&&(g.icon.anchor=new google.maps.Point(d.iconAnchorX,d.iconAnchorY),g.icon.origin=new google.maps.Point(0,0)));g=y.toObject(g);c.overlays.push(g);g.setMap(f.webmap);d.zoomable&&(g.bizId=p.bizId,g.geometry=d.geometry,g.fromTimestamp=p.fromTimestamp,g.toTimestamp=
p.toTimestamp,g.mod=p.moduleName,g.doc=p.documentName,g.infoMarkup=p.infoMarkup,google.maps.event.addListener(g,"click",function(x){f.click(this,x)}))}f._objects[p.bizId]=c}}if(w){k=new google.maps.LatLngBounds;w=!1;for(const l in f._objects)if(Object.prototype.hasOwnProperty.call(f._objects,l)){w=!0;m=f._objects[l].overlays;for(let v=0,q=m.length;v<q;v++)if(p=m[v],p.getPath){p=p.getPath();for(let t=0,x=p.getLength();t<x;t++)k.extend(p.getAt(t))}else p.getPosition&&k.extend(p.getPosition())}w&&(k.getNorthEast().equals(k.getSouthWest())?
(15>f.webmap.getZoom()&&f.webmap.setZoom(15),void 0!==overlay.getPosition&&"function"===typeof overlay.getPosition&&f.webmap.setCenter(k.getNorthEast())):f.webmap.fitBounds(k))}}},centre:function(){y||=new Wkt.Wkt;let f=null;if(SKYVE.Util.mapCentre)try{y.read(SKYVE.Util.mapCentre);const k=y.components[0];f=new google.maps.LatLng(k.y,k.x)}catch(k){console.log(`${SKYVE.Util.mapCentre} is malformed WKT Point format`),SKYVE.Util.mapCentre=null,f=new google.maps.LatLng(0,0)}else f=new google.maps.LatLng(0,
0);return f},scatterValue:function(f,k){y||=new Wkt.Wkt;if(k){try{y.read(k)}catch(d){if("WKTError"===d.name){alert("The WKT string is invalid.");return}}k=y.toObject(f.webmap.defaults);"polygon"!==y.type&&"linestring"!==y.type&&k.setEditable&&k.setEditable(!1);if(Wkt.isArray(k))for(var w in k)Object.prototype.hasOwnProperty.call(k,w)&&!Wkt.isArray(k[w])&&(k[w].setMap(f.webmap),f._overlays.push(k[w]));else k.setMap(f.webmap),f._overlays.push(k);if(void 0!==k.getBounds&&"function"===typeof k.getBounds)f.webmap.fitBounds(k.getBounds());
else if(void 0!==k.getPath&&"function"===typeof k.getPath){w=new google.maps.LatLngBounds;k=k.getPath();for(let d=0,m=k.getLength();d<m;d++)w.extend(k.getAt(d));f.webmap.fitBounds(w)}else 15>f.webmap.getZoom()&&f.webmap.setZoom(15),void 0!==k.getPosition&&"function"===typeof k.getPosition&&f.webmap.setCenter(k.getPosition())}},clear:function(f){for(let k=0,w=f._overlays.length;k<w;k++)f._overlays[k].setMap(null);f._overlays.length=0},drawingTools:function(f){y||=new Wkt.Wkt;f.webmap.drawingManager=
new google.maps.drawing.DrawingManager({drawingControlOptions:{position:google.maps.ControlPosition.LEFT_BOTTOM,drawingModes:H(f.drawingTools)}});f.webmap.drawingManager.setMap(f.webmap);google.maps.event.addListener(f.webmap.drawingManager,"overlaycomplete",function(k){SKYVE.GMap.clear(f);this.setDrawingMode(null);f._overlays.push(k.overlay);y.fromObject(k.overlay);k=y.write();f.setFieldValue(k)})},geoLocator:function(f){if(navigator.geolocation){const k=document.createElement("DIV");Object.assign(k.style,
{backgroundColor:"#fff",border:"2px solid #fff",borderRadius:"3px",boxShadow:"0 2px 6px rgba(0,0,0,.3)",cursor:"pointer",margin:"10px",padding:"5px",textAlign:"center"});k.title="Click to set your current position from your GPS";k.innerHTML='<i class="fa-solid fa-location-crosshairs"></i>';k.index=1;k.addEventListener("click",function(){navigator.geolocation.getCurrentPosition(function(w){SKYVE.GMap.clear(f);f.webmap.drawingManager.setDrawingMode(null);w={lat:w.coords.latitude,lng:w.coords.longitude};
const d=new google.maps.Marker({position:w,map:f.webmap});f._overlays.push(d);f.setFieldValue(`POINT (${w.lng} ${w.lat})`);f.webmap.setZoom(15);f.webmap.setCenter(w)},function(w){alert(w.message)},{enableHighAccuracy:!0})});f.webmap.geolocator=k;f.webmap.controls[google.maps.ControlPosition.LEFT].push(k)}},setDisabled:function(f,k){f.webmap&&(f.webmap.drawingManager&&f.webmap.drawingManager.setOptions({drawingControl:!k}),f.webmap.geolocator&&(f.webmap.geolocator.style.display=k?"none":"block"))},
refreshControls:function(f){const k=document.createElement("DIV");Object.assign(k.style,{backgroundColor:"#fff",border:"2px solid #fff",borderRadius:"3px",boxShadow:"0 2px 6px rgba(0,0,0,.3)",cursor:"pointer",margin:"10px",padding:"5px",textAlign:"center"});k.title="Click to set the refresh rate of the map";k.innerHTML=`
						        <input type="number" min="0" max="500" step="1" value="${f.refreshTime}" size="3" />
						        <input type="checkbox" ${f._refreshRequired?"checked":""}><label>Refresh</label>
						    `;k.index=1;k.children[0].addEventListener("change",function(){f.refreshTime=Number(this.value);f._refreshRequired&&(f._intervalId&&clearInterval(f._intervalId),f._intervalId=setInterval(f.rerender.bind(f),1E3*f.refreshTime))});k.children[1].addEventListener("click",function(){f._refreshRequired=this.checked;f._intervalId&&(clearInterval(f._intervalId),f._intervalId=null);f._refreshRequired&&(f.rerender(),f._intervalId=setInterval(f.rerender.bind(f),1E3*f.refreshTime))});f.webmap.controls[google.maps.ControlPosition.LEFT_BOTTOM].push(k)}}}();
SKYVE.Leaflet=function(){function y(c){function g(r){r=K.substring(M).match(r);if(!r)return null;M+=r[0].length;return r[0]}function l(){g(/^\s*/)}function v(){l();let r=0;const B=[],I=[B];let N=B,O;for(;O=g(/^(\()/)||g(/^(\))/)||g(/^(,)/)||g(p);){if("("===O)I.push(N),N=[],I[I.length-1].push(N),r++;else if(")"===O){if(0===N.length)return null;N=I.pop();if(!N)return null;r--;if(0===r)break}else if(","===O)N=[],I[I.length-1].push(N);else{if(O.split(/\s/g).some(isNaN))return null;Array.prototype.push.apply(N,
O.split(/\s/g).map(parseFloat))}l()}return 0!==r?null:B}function q(){const r=[];let B=[],I;for(;I=g(p)||g(/^(,)/);)","===I?(r.push(B),B=[]):I.split(/\s/g).some(isNaN)||(B||=[],Array.prototype.push.apply(B,I.split(/\s/g).map(parseFloat))),l();if(B)r.push(B);else return null;return r.length?r:null}function t(){if(!g(/^(point(\sz)?)/i))return null;l();if(!g(/^(\()/))return null;const r=q();if(!r)return null;l();return g(/^(\))/)?{type:"Point",coordinates:r[0]}:null}function x(){if(!g(/^(multipoint)/i))return null;
l();K=`MULTIPOINT (${K.substring(K.indexOf("(")+1,K.length-1).replace(/\(/g,"").replace(/\)/g,"")})`;const r=v();if(!r)return null;l();return{type:"MultiPoint",coordinates:r}}function A(){if(!g(/^(multilinestring)/i))return null;l();const r=v();if(!r)return null;l();return{type:"MultiLineString",coordinates:r}}function G(){if(!g(/^(linestring(\sz)?)/i))return null;l();if(!g(/^(\()/))return null;const r=q();return r&&g(/^(\))/)?{type:"LineString",coordinates:r}:null}function D(){const r=[];let B;if(!g(/^(geometrycollection)/i))return null;
l();if(!g(/^(\()/))return null;for(;B=z();)r.push(B),l(),g(/^(,)/),l();return g(/^(\))/)?{type:"GeometryCollection",geometries:r}:null}function z(){var r;(r=t()||G())||(g(/^(polygon(\sz)?)/i)?(l(),r=(r=v())?{type:"Polygon",coordinates:r}:null):r=null);(r=r||x()||A())||(g(/^(multipolygon)/i)?(l(),r=(r=v())?{type:"MultiPolygon",coordinates:r}:null):r=null);return r||D()}c=c.split(";");let K=c.pop();const C=(c.shift()||"").split("=").pop();let M=0;return function(r){r&&C.match(/\d+/)&&(r.crs={type:"name",
properties:{name:`urn:ogc:def:crs:EPSG::${C}`}});return r}(z())}function H(c){function g(t){return t.join(" ")}function l(t){return t.map(g).join(", ")}function v(t){return t.map(l).map(q).join(", ")}function q(t){return`(${t})`}"Feature"===c.type&&(c=c.geometry);switch(c.type){case "Point":return`POINT (${g(c.coordinates)})`;case "LineString":return`LINESTRING (${l(c.coordinates)})`;case "Polygon":return`POLYGON (${v(c.coordinates)})`;case "MultiPoint":return`MULTIPOINT (${l(c.coordinates)})`;case "MultiPolygon":return`MULTIPOLYGON (${c.coordinates.map(v).map(q).join(", ")})`;
case "MultiLineString":return`MULTILINESTRING (${v(c.coordinates)})`;case "GeometryCollection":return`GEOMETRYCOLLECTION (${c.geometries.map(H).join(", ")})`;default:throw Error("stringify requires a valid GeoJSON Feature or geometry object as input");}}function f(c,g,l){if(l&&(l=c.webmap.getMaxZoom(),isFinite(l)?(c._markerClusterGroup&&c._markerClusterGroup._map===c.webmap||(c._markerClusterGroup=L.markerClusterGroup({showCoverageOnHover:!0,zoomToBoundsOnClick:!0,spiderfyOnMaxZoom:!0,removeOutsideVisibleBounds:!0,
maxClusterRadius:40,spiderLegPolylineOptions:{weight:1.5,color:"#333",opacity:.5}}),c.webmap.addLayer(c._markerClusterGroup)),l=c._markerClusterGroup):l=null,l)){g._skyveClustered=!0;l.addLayer(g);return}c.webmap.addLayer(g)}function k(c,g){g._skyveClustered&&c._markerClusterGroup?c._markerClusterGroup.removeLayer(g):c.webmap.removeLayer(g)}function w(c){return c.zoomData?c.zoomData.geometry:c.getLayers&&(c=c.getLayers(),c.length&&c[0].zoomData)?c[0].zoomData.geometry:null}function d(c){return c.getBounds?
c.getBounds():c.getLatLng?(c=c.getLatLng(),L.latLngBounds(c,c)):null}const m=/[-+]?([0-9]*\.[0-9]+|[0-9]+)([eE][-+]?[0-9]+)?/,p=new RegExp("^"+m.source+"(\\s"+m.source+"){1,}");return{scatter:function(c,g,l,v){var q=g.items;if(q){if(v)for(var t in c._objects){if(Object.prototype.hasOwnProperty.call(c._objects,t)){var x=!1;for(let A=0,G=q.length;A<G;A++)if(q[A].bizId===t){x=!0;break}if(!x){x=c._objects[t];for(let A=0,G=x.overlays.length;A<G;A++)k(c,x.overlays[A]),x.overlays[A]=null;delete x.overlays;
delete c._objects[t]}}}else for(x in c._objects)if(Object.prototype.hasOwnProperty.call(c._objects,x)){t=c._objects[x];for(let A=0,G=t.overlays.length;A<G;A++)k(c,t.overlays[A]),t.overlays[A]=null;delete t.overlays;delete c._objects[x]}for(let A=0,G=q.length;A<G;A++){const D=q[A];if(t=c._objects[D.bizId]){if(x=t.overlays.length===D.features.length)for(let z=0,K=t.overlays.length;z<K;z++)if(w(t.overlays[z])!==D.features[z].geometry){x=!1;break}if(!x){for(let z=0,K=t.overlays.length;z<K;z++)k(c,t.overlays[z]),
t.overlays[z]=null;delete t.overlays;delete c._objects[D.bizId];t=null}}if(!t){t={overlays:[]};for(let z=0,K=D.features.length;z<K;z++){const C=D.features[z];x=y(C.geometry);x.properties={editable:C.editable};C.strokeColour&&(x.properties.color=C.strokeColour);C.fillColour&&(x.properties.fillColor=C.fillColour);C.fillOpacity&&(x.properties.fillOpacity=C.fillOpacity);C.iconRelativeFilePath&&(v={iconUrl:`${SKYVE.Util.CONTEXT_URL}resources?_n=${C.iconRelativeFilePath}&_doc=${g._doc}`},C.iconAnchorX&&
C.iconAnchorY&&(v.iconAnchor=[C.iconAnchorX,C.iconAnchorY]),x.properties.icon=v);v=x&&("Point"===x.type||"MultiPoint"===x.type)&&x.properties&&!x.properties.editable&&L.markerClusterGroup;x=L.geoJson(x,{pointToLayer(M,r){const B=M.properties;delete M.properties;B.icon&&(B.icon=L.icon(B.icon));return L.marker(r,B)},style:function(M){const r=M.geometry.properties;delete M.geometry.properties;return r},onEachFeature:function(M,r){C.zoomable&&(r.zoomData={bizId:D.bizId,geometry:C.geometry,fromTimestamp:D.fromTimestamp,
toTimestamp:D.toTimestamp,mod:D.moduleName,doc:D.documentName,infoMarkup:D.infoMarkup},r.bindPopup(function(B){return c.click(B)}))}});t.overlays.push(x);f(c,x,v)}c._objects[D.bizId]=t}}if(l){g=L.latLngBounds();l=!1;for(const A in c._objects)if(Object.prototype.hasOwnProperty.call(c._objects,A)){l=!0;q=c._objects[A].overlays;for(let G=0,D=q.length;G<D;G++)(t=d(q[G]))&&g.extend(t)}l&&c.webmap.fitBounds(g,{maxZoom:15})}}},centre:function(){let c=[0,0];if(SKYVE.Util.mapCentre)try{const g=y(SKYVE.Util.mapCentre);
c=[g.coordinates[1],g.coordinates[0]]}catch(g){console.log(`${SKYVE.Util.mapCentre} is malformed WKT Point format`),SKYVE.Util.mapCentre=null}return c},scatterValue:function(c,g){if(g){var l=null;try{l=L.geoJson(y(g))}catch(v){console.log(`The WKT string ${g} is invalid.`);return}l.addTo(c.webmap);c._overlays.push(l);c.webmap.fitBounds(l.getBounds(),{maxZoom:15})}},clear:function(c){for(let g=0,l=c._overlays.length;g<l;g++)c.webmap.removeLayer(c._overlays[g]);c._overlays.length=0},drawingTools:function(c){const g=
c.drawingTools;L.EditControl=L.Control.extend({options:{position:"topright"},onAdd:function(l){const v=L.DomUtil.create("div","leaflet-control leaflet-bar");if(!g||"point"===g||"pointAndLine"===g||"pointAndPolygon"===g){var q=L.DomUtil.create("a","",v);q.href="#";q.title="Create a new marker";q.innerHTML='<i class="fa-solid fa-location-dot"></i>';L.DomEvent.on(q,"click",L.DomEvent.stop).on(q,"click",function(){window.LAYER=c.webmap.editTools.startMarker.call(l.editTools)},this)}g&&"line"!==g&&"pointAndLine"!==
g&&"lineAndPolygon"!==g||(q=L.DomUtil.create("a","",v),q.href="#",q.title="Create a new line",q.innerHTML='<i class="fa-solid fa-diagram-project"></i>',L.DomEvent.on(q,"click",L.DomEvent.stop).on(q,"click",function(){window.LAYER=c.webmap.editTools.startPolyline.call(l.editTools)},this));g&&"polygon"!==g&&"pointAndPolygon"!==g&&"lineAndPolygon"!==g||(q=L.DomUtil.create("a","",v),q.href="#",q.title="Create a new rectangle",q.innerHTML='<i class="fa-solid fa-vector-square"></i>',L.DomEvent.on(q,"click",
L.DomEvent.stop).on(q,"click",function(){window.LAYER=c.webmap.editTools.startRectangle.call(l.editTools)},this),q=L.DomUtil.create("a","",v),q.href="#",q.title="Create a new polygon",q.innerHTML='<i class="fa-solid fa-draw-polygon"></i>',L.DomEvent.on(q,"click",L.DomEvent.stop).on(q,"click",function(){window.LAYER=c.webmap.editTools.startPolygon.call(l.editTools)},this));return v}});c.webmap.editControl=new L.EditControl;c.webmap.addControl(c.webmap.editControl);c.webmap.on("editable:drawing:commit",
function(l){SKYVE.Leaflet.clear(c);l.layer.toggleEdit();c._overlays.push(l.layer);c.setFieldValue(H(l.layer.toGeoJSON(12)))})},geoLocator:function(c){navigator.geolocation&&(L.GeoControl=L.Control.extend({options:{position:"bottomleft"},onAdd:function(g){g=L.DomUtil.create("div","leaflet-control leaflet-bar");const l=L.DomUtil.create("a","",g);l.href="#";l.title="Click to set your current position from your GPS";l.innerHTML='<i class="fa-solid fa-location-crosshairs"></i>';L.DomEvent.on(l,"click",
L.DomEvent.stop).on(l,"click",function(){c.webmap.editTools.drawing()&&c.webmap.editTools.commitDrawing();navigator.geolocation.getCurrentPosition(function(v){SKYVE.Leaflet.clear(c);const q=[v.coords.latitude,v.coords.longitude],t=L.marker(q);t.addTo(c.webmap);c._overlays.push(t);c.setFieldValue(`POINT (${v.coords.longitude} ${v.coords.latitude})`);c.webmap.setZoom(15);c.webmap.panTo(q)},function(v){alert(v.message)},{enableHighAccuracy:!0})},this);return g}}),c.webmap.geoControl=new L.GeoControl,
c.webmap.addControl(c.webmap.geoControl))},setDisabled:function(c,g){c.webmap&&(c.webmap.editControl&&(c.webmap.editControl.getContainer().style.display=g?"none":"block"),c.webmap.geoControl&&(c.webmap.geoControl.getContainer().style.display=g?"none":"block"))},refreshControls:function(c){L.GeoControl=L.Control.extend({options:{position:"bottomleft"},onAdd:function(g){g=L.DomUtil.create("div","leaflet-control");g.innerHTML=`
		                <input type="number" min="0" max="500" step="1" value="${c.refreshTime}" size="3" />
		                <input type="checkbox" ${c._refreshRequired?"checked":""}><label>Refresh</label>
		            `;g.children[0].addEventListener("change",function(){c.refreshTime=Number(this.value);c._refreshRequired&&(c._intervalId&&clearInterval(c._intervalId),c._intervalId=setInterval(c.rerender.bind(c),1E3*c.refreshTime))});g.children[1].addEventListener("click",function(){c._refreshRequired=this.checked;c._intervalId&&(clearInterval(c._intervalId),c._intervalId=null);c._refreshRequired&&(c.rerender(),c._intervalId=setInterval(c.rerender.bind(c),1E3*c.refreshTime))});return g}});c.webmap.addControl(new L.GeoControl)}}}();SKYVE.PF=function(){var y=!1,H=function(){var a=sessionStorage.sessionHistory;return a=a?JSON.parse(a):[]},f={},k={},w={},d=0,m=0,p=0,c="",g="",l="",v="",q="",t="",x="",A=function(a){if(!a)return null;if(a.jquery)return a[0]||null;if(a.target)return a.currentTarget||a.target;if("string"===typeof a){var b=$(PrimeFaces.escapeClientId(a));0===b.length&&(b=$(a));return b[0]||null}return a},G=function(){"function"===typeof window.Event?window.dispatchEvent(new Event("scroll")):$(window).trigger("scroll")},
D=function(a){if(a&&a.jq&&a.stickyContainer){var b=a.jq.children(".ui-datatable-tablewrapper").children("table");0===b.length&&(b=a.jq.find("> .ui-datatable-tablewrapper table").first());if(0!==b.length){var e=b.offset();e&&(b=b.outerWidth(),a.stickyContainer.css({left:e.left+"px",width:b+"px"}),a.stickyContainer.children("table").css("width",b+"px"))}}},z=function(a){D(a);G();D(a)},K=function(a,b){a&&(a.skyveStickyRefreshTimeout&&window.clearTimeout(a.skyveStickyRefreshTimeout),a.skyveStickyRefreshTimeout=
window.setTimeout(function(){a.skyveStickyRefreshTimeout=null;z(a)},b))},C=function(a){z(a);window.setTimeout(function(){z(a)},0);window.setTimeout(function(){z(a)},50);window.setTimeout(function(){z(a)},250)},M=function(a){if(a&&!a.skyveStickyResizePatch){var b=".skyveStickyHeader-"+a.id.replace(/\W/g,"_");$(window).on("resize"+b+" orientationchange"+b,function(){z(a);K(a,80);window.setTimeout(function(){z(a)},250)});$(document).on("click"+b,".layout-menu-button,.menu-button,#topbar-menu-button",
function(){z(a);window.setTimeout(function(){z(a)},250)});a.addDestroyListener(function(){a.skyveStickyRefreshTimeout&&(window.clearTimeout(a.skyveStickyRefreshTimeout),a.skyveStickyRefreshTimeout=null);$(window).off(b);$(document).off(b)});a.skyveStickyResizePatch=!0}},r=function(){var a=window.PrimeFaces&&PrimeFaces.widget&&PrimeFaces.widget.DataTable&&PrimeFaces.widget.DataTable.prototype;if(a&&!a.skyveStickyFilterPatch){var b=a.setupStickyHeader;"function"===typeof b&&(a.setupStickyHeader=function(){b.apply(this,
arguments);M(this);C(this)},a.skyveStickyFilterPatch=!0)}};r();$(r);var B=function(a,b,e){var h=A(a);a=A(b);if(!h||!a||window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches)return null;b=h.getBoundingClientRect();h=a.getBoundingClientRect();if(0>=b.width||0>=b.height||0>=h.width||0>=h.height)return null;e=e||{};var n=a;if(e.ghost||a.classList.contains("ui-dialog")){var u=document.createElement("div"),E=window.getComputedStyle(a);a=parseInt(E.zIndex,10);var F=E.backgroundColor;
u.className="skyveMorphGhost";u.style.left=h.left+"px";u.style.top=h.top+"px";u.style.width=h.width+"px";u.style.height=h.height+"px";u.style.backgroundColor=F&&"rgba(0, 0, 0, 0)"!==F&&"transparent"!==F?F:"#fff";u.style.borderRadius=E.borderRadius;u.style.zIndex=isNaN(a)?"1000":a+1;document.body.appendChild(u);a=u;e.endRadius=e.endRadius||E.borderRadius}u=Math.min(Math.abs(b.left-h.left),Math.abs(b.right-h.left))<=Math.min(Math.abs(b.left-h.right),Math.abs(b.right-h.right))?"left":"right";E=Math.min(Math.abs(b.top-
h.top),Math.abs(b.bottom-h.top))<=Math.min(Math.abs(b.top-h.bottom),Math.abs(b.bottom-h.bottom))?"top":"bottom";F=Math.max(b.width/h.width,.02);var P=Math.max(b.height/h.height,.02),W=b.left-h.left-("left"===u?0:h.width)*(1-F);h=b.top-h.top-("top"===E?0:h.height)*(1-P);a.style.setProperty("--skyve-morph-origin",u+" "+E);a.style.setProperty("--skyve-morph-x",W+"px");a.style.setProperty("--skyve-morph-y",h+"px");a.style.setProperty("--skyve-morph-scale-x",F);a.style.setProperty("--skyve-morph-scale-y",
P);a.style.setProperty("--skyve-morph-start-radius",e.startRadius||Math.round(Math.min(b.width,b.height)/2)+"px");e.endRadius?a.style.setProperty("--skyve-morph-end-radius",e.endRadius):a.style.removeProperty("--skyve-morph-end-radius");return{element:a,originalElement:n,settings:e}},I=function(a,b,e){if(a=B(a,b,e)){var h=a.element,n=a.originalElement,u=a.settings;u.hideTargetDuring&&n!==h&&(n.style.visibility="hidden");h.classList.remove("skyveMorphOpening");h.classList.add("skyveMorphOpening");
window.setTimeout(function(){h.classList.remove("skyveMorphOpening");u.hideTargetDuring&&n!==h&&(n.style.visibility="");h.classList.contains("skyveMorphGhost")&&h.parentNode.removeChild(h)},u.duration||360)}},N=function(a,b,e){window.setTimeout(function(){var h=window.PF?window.PF(b):null;I(a,h&&h.jq?h.jq[0]:null,e)},0)},O=function(){var a=document.body,b=document.documentElement;if(a&&b){if(0===d){m=window.pageXOffset||b.scrollLeft||a.scrollLeft||0;p=window.pageYOffset||b.scrollTop||a.scrollTop||
0;c=b.style.overflow;g=a.style.overflow;l=a.style.position;v=a.style.top;q=a.style.left;t=a.style.width;x=a.style.paddingRight;var e=window.innerWidth-b.clientWidth;b.style.overflow="hidden";a.style.overflow="hidden";a.style.position="fixed";a.style.top=-p+"px";a.style.left=-m+"px";a.style.width="100%";0<e&&(a.style.paddingRight=(parseFloat(window.getComputedStyle(a).paddingRight)||0)+e+"px")}d++}},Z=function(){var a=document.body,b=document.documentElement;a&&b&&0!==d&&(d=Math.max(0,d-1),0===d&&
(b.style.overflow=c,a.style.overflow=g,a.style.position=l,a.style.top=v,a.style.left=q,a.style.width=t,a.style.paddingRight=x,window.scrollTo(m,p)))},aa=function(a){var b=a.id?a.id.replace(/_button$/,"_menu"):null;b=b?document.getElementById(b):null;!b&&a.parentNode&&(b=$(a.parentNode).children(".skyveContentActionMenu")[0]||null);return b};$(document).on("mousedown touchstart",".skyveContentActionButton",function(){var a=aa(this);$(this).data("skyveMenuWasVisible",!(!a||!$(a).is(":visible")))});
$(document).on("click",".skyveContentActionButton",function(){if(!$(this).data("skyveMenuWasVisible")){var a=this;window.setTimeout(function(){var b=aa(a);b&&$(b).is(":visible")&&I(a,b,{duration:360,endRadius:"4px",ghost:!0,hideTargetDuring:!0})},0)}});var ba=function(a){return a.replace(/_(\d*)_/g,"[$1]").replace(/_/g,".")},X=function(a,b,e){a=a?a+"_"+b+e:"_"+b+e;return'[id="'+a+'"],[id$=":'+a+'"]'},J=function(a,b,e,h){var n=[e],u=e.lastIndexOf("_");-1<u&&u<e.length-1&&(u=e.substring(u+1),"_"===
e.charAt(0)&&n.push("_"+u),n.push(u));e=a.$();u=0;for(var E=n.length;u<E;u++)if(e=a.$(X(b,n[u],h)),0<e.length)return e;if(b)for(b=0,u=n.length;b<u&&!(e=a.$(X(null,n[b],h)),0<e.length);b++);return e},Q=function(a,b,e,h,n){J(a,b,e,h).val(n).attr("value",n).trigger("change")},R=function(a,b,e,h,n){a=a.$(X(b,e,h));0<a.length&&a.val(n).attr("value",n).trigger("change")},ca=function(a,b,e){J(a,b,e,"_link").attr("href","javascript:void(0)").text("<Empty>").attr("onclick","return false").off("click.skyveContentClear").on("click.skyveContentClear",
function(){return!1})},ka=function(a,b,e,h){J(a,b,e,"_video").each(function(){var n=a.$(this),u=n.children("video");0<u.length?u.attr("src",h):n.append('<video controls preload="metadata" style="width:100%;height:100%;object-fit:contain" src="'+h+'"></video>')})},da=function(a,b,e){J(a,b,e,"_video").each(function(){a.$(this).children("video").remove()})},S=function(a,b,e,h){a=J(a,b,e,"_image");a.toggleClass("skyveContentHidden",h);a.parent().toggleClass("skyveContentEmpty",h)},T=function(a,b,e,h){J(a,
b,e,"_link").toggleClass("skyveContentHidden",!!h&&"link"!==h);var n=J(a,b,e,"_image"),u="image"===h;n.toggleClass("skyveContentHidden",!u);n.parent().toggleClass("skyveContentHidden",!u);n.parent().toggleClass("skyveContentEmpty",!u);a=J(a,b,e,"_video");h="video"===h;a.toggleClass("skyveContentHidden",!h);a.parent().toggleClass("skyveContentHidden",!h)},U=function(a,b,e,h){b=b?a.$(".skyveContentMarkupAction-"+b+"_"+e):a.$();a=0<b.length?b:a.$(".skyveContentMarkupAction-"+e);a.toggleClass("skyveContentHidden",
"image"!==h)},ea=function(a,b,e){return(a?window.PF(a+"_"+b+e):null)||window.PF(b+e)};return{getById:function(a){return $(PrimeFaces.escapeClientId(a))},morphFrom:function(a,b,e){I(a,b,e)},morphWidgetFrom:function(a,b,e){N(a,b,e)},lockPageScroll:function(){O()},unlockPageScroll:function(){Z()},getByIdEndsWith:function(a){return $('[id$="'+a+'"]')},contentOverlayOnShow:function(a,b,e){e&&O();(e=(e=RegExp("[?&]_n=([^&]*)").exec(b))?decodeURIComponent(e[1].replace(/\+/g," ")):null)&&(f[e]=a);a=SKYVE.PF.getById(a+
"_overlayiframe");a.attr("src")!==b&&a.attr("src",b)},contentOverlayOnHide:function(a,b,e){b||SKYVE.PF.getById(a+"_overlayiframe").attr("src","");e&&Z()},afterContentUpload:function(a,b,e,h,n,u){h=f[a];Q(window,h,a,"_hidden",b);n&&u&&R(window,h,u,"_hidden",n);b="content?_n="+b+"&_doc="+e+"&_b="+ba(a);J(window,h,a,"_link").off("click.skyveContentClear").attr("href",b).text("Content").attr("onclick","return true");J(window,h,a,"_image").attr("src",b);S(window,h,a,!1);ka(window,h,a,b);u&&T(window,h,
a,n);U(window,h,a,n);(n=ea(h,a,"Overlay"))&&n.hide();SKYVE.PF.getById(h+"_overlayiframe").attr("src","");delete f[a]},clearContentImage:function(a,b,e){Q(window,b,a,"_hidden","");e&&R(window,b,e,"_hidden","");ca(window,b,a);J(window,b,a,"_image").attr("src","images/blank.gif");S(window,b,a,!0);da(window,b,a);e&&T(window,b,a,"");U(window,b,a,"")},clearContentLink:function(a,b,e){Q(window,b,a,"_hidden","");e&&R(window,b,e,"_hidden","");ca(window,b,a);da(window,b,a);e&&T(window,b,a,"");U(window,b,a,
"")},clearContent:function(a,b,e){SKYVE.PF.clearContentLink(a,b,e);J(window,b,a,"_image").attr("src","images/blank.gif");S(window,b,a,!0)},contentMarkupOnShow:function(a,b,e,h){k[b]=a;h&&(w[b]=h);b=e+("&_id="+J(window,a,b,"_hidden").val());SKYVE.PF.getById(a+"_markupiframe").attr("src",b)},contentMarkupOnHide:function(a){SKYVE.PF.getById(a+"_markupiframe").attr("src","")},afterMarkupApply:function(a,b,e,h){h=k[a];Q(window,h,a,"_hidden",b);var n=w[a];n&&R(window,h,n,"_hidden","image");b="content?_n="+
b+"&_doc="+e+"&_b="+ba(a);J(window,h,a,"_link").off("click.skyveContentClear").attr("href",b).text("Content").attr("onclick","return true");J(window,h,a,"_image").attr("src",b);S(window,h,a,!1);n&&T(window,h,a,"image");U(window,h,a,"image");(b=ea(h,a,"Markup"))&&b.hide();delete k[a];delete w[a]},tabChange:function(a,b,e,h){sessionStorage["tab_"+a+"_"+b+"_"+e]=h;SKYVE.BizMap&&SKYVE.BizMap.resizeAll();SKYVE.BizMapPicker&&SKYVE.BizMapPicker.resizeAll()},getTextElement:function(a){return SKYVE.PF.getById(a)},
getTextValue:function(a){return SKYVE.PF.getTextElement(a).val()},setTextValue:function(a,b){SKYVE.PF.getTextElement(a).val(b)},getPasswordElement:function(a){return SKYVE.PF.getById(a+"password")},getPasswordValue:function(a){return SKYVE.PF.getPasswordElement(a).val()},setPasswordValue:function(a,b){SKYVE.PF.getPasswordElement(a).val(b)},getComboElement:function(a){return SKYVE.PF.getById(a)},getLookupElement:function(a){return SKYVE.PF.getById(a)},getLookupValue:function(a){return SKYVE.PF.getById(a+
"_hinput").val()},setLookupValue:function(a,b){SKYVE.PF.getById(a+"_hinput").val(b)},getLookupDescription:function(a){return SKYVE.PF.getById(a+"_input").val()},setLookupDescription:function(a,b){SKYVE.PF.getById(a+"_input").val(b)},getCheckboxElement:function(a){return SKYVE.PF.getById(a)},getCheckboxValue:function(a){var b=SKYVE.PF.getById(a+"_input").val();return"0"==b?null:"1"==b?!0:"2"==b?!1:SKYVE.PF.getById(a+"_input").is(":checked")},setCheckboxValue:function(a,b){SKYVE.PF.getById(a+"_input").prop("checked",
b);a=SKYVE.PF.getById(a).find(".ui-chkbox-box");var e=a.find(".ui-chkbox-icon");b?(a.addClass("ui-state-active"),e.addClass("ui-icon ui-icon-check")):(a.removeClass("ui-state-active"),e.removeClass("ui-icon ui-icon-check"))},establishHistory:function(){var a=H();if(0==a.length){var b=window.location.href;if(b.match(/.*[\?|&]a=e.*/)||b.match(/.*[\?|&]a=e&.*/)){var e=document.referrer;e&&""!=e&&e!=b||(e=SKYVE.Util.CONTEXT_URL);a.push(e);sessionStorage.sessionHistory=JSON.stringify(a)}}},startHistory:function(a){sessionStorage.sessionHistory=
"[]";window.location.assign(a)},pushHistory:function(a){var b=H();b.push(window.location.href);sessionStorage.sessionHistory=JSON.stringify(b);a&&window.location.assign(a)},popHistory:function(a){var b=H();if(0<b.length){var e=b.pop();sessionStorage.sessionHistory=JSON.stringify(b);a&&window.location.assign(e)}},saveHistory:function(a,b,e){for(var h=H(),n=!1,u=0;u<h.length;u++){for(var E=h[u],F=E.split(/\?|&/),P="m="+a,W="d="+b,fa=!1,ha=!1,ia=!1,ja=!1,Y=0;Y<F.length;Y++){var V=F[Y];"a=e"==V?fa=!0:
V==P?ha=!0:V==W?ia=!0:V.startsWith("i=")&&(ja=!0)}fa&&ha&&ia&&ja&&(E+="&i="+e,h[u]=E,n=!0)}n&&(sessionStorage.sessionHistory=JSON.stringify(h));window.history&&history.replaceState&&(E=window.location.href+"&i="+e,history.replaceState({},"",E))},toggleFilters:function(a){a=$('[id$="'+a+'"]');if(null!=a){var b=function(){var e=$(this);e.hasClass("hiddenFilter")?e.removeClass("hiddenFilter"):e.addClass("hiddenFilter")};a.find(".ui-filter-column").each(b);a.find(".ui-column-customfilter").each(b);G()}},
onPushMessage:function(a){for(var b=[],e=0,h=a.length;e<h;e++){var n=a[e];if("g"==n.type)b.push({severity:n.severity,summary:n.message});else if("m"==n.type)PrimeFaces.showMessageInDialog({severity:n.severity,summary:"",detail:n.message,escape:!1});else if("r"==n.type)pushRerender();else if("j"==n.type)window[n.method](n.argument)}0<b.length&&PrimeFaces.cw("Growl","pushGrowl",{id:"pushGrowl",widgetVar:"pushGrowl",life:6E3,sticky:!1,msgs:b})},gmap:function(a){if(y)setTimeout(function(){SKYVE.PF.gmap(a)},
100);else{if(window.google&&window.google.maps&&window.SKYVE.BizMapPicker)return a.queryName||a.modelName?SKYVE.BizMap.create(a):SKYVE.BizMapPicker.create(a);y=!0;SKYVE.Util.loadJS("wicket/wicket.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("wicket/wicket-gmap3.js?v="+SKYVE.Util.v,function(){var b="https://maps.googleapis.com/maps/api/js?v=3&libraries=drawing";SKYVE.Util.googleMapsV3ApiKey&&(b+="&key="+SKYVE.Util.googleMapsV3ApiKey);SKYVE.Util.loadJS(b,function(){SKYVE.Util.loadJS("skyve/prime/skyve-gmap-min.js?v="+
SKYVE.Util.v,function(){y=!1;return a.queryName||a.modelName?SKYVE.BizMap.create(a):SKYVE.BizMapPicker.create(a)})})})})}},leaflet:function(a){if(y)setTimeout(function(){SKYVE.PF.leaflet(a)},100);else{if(window.L&&window.SKYVE.BizMapPicker)return a.queryName||a.modelName?SKYVE.BizMap.create(a):SKYVE.BizMapPicker.create(a);y=!0;SKYVE.Util.loadCSS("leaflet/leaflet.css?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/leaflet.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/Path.Drag.js?v="+
SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/Leaflet.Editable.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadCSS("leaflet/MarkerCluster.css?v="+SKYVE.Util.v,function(){SKYVE.Util.loadCSS("leaflet/MarkerCluster.Default.css?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/leaflet.markercluster.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadCSS("leaflet/leaflet.fullscreen.css?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/Leaflet.fullscreen.min.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("skyve/prime/skyve-leaflet-min.js?v="+
SKYVE.Util.v,function(){y=!1;return a.queryName||a.modelName?SKYVE.BizMap.create(a):SKYVE.BizMapPicker.create(a)})})})})})})})})})})}},chartExtender:function(){this.cfg.config.options||(this.cfg.config.options={});this.cfg.config.options.responsive=!0;this.cfg.config.options.maintainAspectRatio=!1},sidebar:function(a,b,e,h,n){$(function(){var u=$(window),E=$("head");$("body");var F=$("#"+a);F.children(".inner");0==$("#sidebarStyle"+n).length&&$('<style id="sidebarStyle'+n+'">.sidebar'+n+"{background-color:white;font-size:0.9em;position:relative;width:"+
b+";flex-grow:0;flex-shrink:0;transition:margin-right 0.5s ease,box-shadow 0.5s ease;}.sidebar"+n+" .toggle{text-decoration:none;transition:right 0.5s ease;-webkit-tap-highlight-color:rgba(255,255,255,0);border:0;display:none;position:absolute;top:calc(50% - 3.75em);right:calc("+h+"px - 3em);width:4em;height:7.5em;line-height:6.25em;text-align:center;z-index:10000;}.sidebar"+n+" .toggle:before{font-family:FontAwesome;font-size:1.1rem;font-style:normal;font-weight:normal;text-transform:none !important;content:'>';height:inherit;right:0;line-height:inherit;position:absolute;text-indent:0;top:0;width:inherit;color:#7f888f;margin-right:1.5em;margin-top:-0.5em;z-index:1;}.sidebar"+
n+" .toggle:after{background:rgba(222,225,226,0.75);border-radius:0.375em;content:'';height:3em;right:2em;position:absolute;top:1em;width:3em;}.sidebar"+n+".inactive{margin-right:-"+h+"px;}.sidebar"+n+".inactive .toggle:before{content:'<';}@media screen and (max-width:"+e+"px){.sidebar"+n+"{box-shadow:0 0 5em 0 rgba(0,0,0,0.175);position:fixed;top:0;right:0;width:"+h+"px;height:100%;z-index:10000;}.sidebar"+n+".inactive{box-shadow:none;}.sidebar"+n+">.inner{position:absolute;top:0;right:0;width:100%;height:100%;overflow-x:hidden;overflow-y:auto;-webkit-overflow-scrolling:touch;}.sidebar"+
n+" .toggle{display:flex;}}</style>").appendTo(E);u.on("resize",function(){u.width()<=e?F.addClass("inactive"):F.removeClass("inactive")});u.trigger("resize");$('<a href="#'+a+'" class="toggle"></a>').appendTo(F).on("click",function(P){P.preventDefault();P.stopPropagation();F.toggleClass("inactive")});window.setTimeout(function(){F.show()},100)})}}}();
(function(){function y(w,d){var m=d.container.getBoundingClientRect().width;if(!(0>=m||m===d.lastWidth)){d.lastWidth=m;var p=parseFloat(getComputedStyle(w).getPropertyValue("--skyve-card-breakpoint"))||0;if(w.classList.contains("skyve-card-grid-active")){if(m<Math.max(p,d.minimumTableWidth))return;w.classList.remove("skyve-card-grid-active")}var c=w.querySelector(".ui-datatable-tablewrapper");if(c&&0<c.clientWidth){var g=c.scrollWidth>c.clientWidth+1;m<p||g?(d.minimumTableWidth=g?Math.max(m+1,c.scrollWidth):
0,w.classList.add("skyve-card-grid-active")):d.minimumTableWidth=0}else d.lastWidth=null}}function H(w){k.forEach(function(d,m){document.contains(m)&&m.parentElement===d.container||(d.observer.disconnect(),k.delete(m))});document.querySelectorAll(".skyve-card-grid").forEach(function(d){if(d.parentElement){var m=k.get(d);if(m)w&&(d.classList.remove("skyve-card-grid-active"),m.minimumTableWidth=0,m.lastWidth=null,y(d,m));else{m={container:d.parentElement,minimumTableWidth:0,lastWidth:null};var p=new ResizeObserver(function(){y(d,
m)});m.observer=p;p.observe(m.container);k.set(d,m);y(d,m)}}})}function f(){H(!1);$(document).on("pfAjaxComplete",function(){H(!0)})}var k=new Map;"loading"===document.readyState?document.addEventListener("DOMContentLoaded",f):f()})();
//# sourceMappingURL=skyve-min.js.map
