window.SKYVE||(window.SKYVE={});
SKYVE.Util=function(){const r=function(q,a){a!==null&&(q.readyState?q.onreadystatechange=function(){if(q.readyState==="loaded"||q.readyState==="complete")q.onreadystatechange=null,a()}:q.onload=a);const c=document.getElementsByTagName("HEAD")[0];c&&c.appendChild(q)};return{customer:null,v:null,googleMapsV3ApiKey:null,ckEditorConfigFileUrl:null,mapCentre:null,mapZoom:1,CONTEXT_URL:`${window.location}`.substring(0,`${window.location}`.lastIndexOf("/")+1),allowedReportFormats:null,loadJS:function(q,
a){const c=document.createElement("SCRIPT");c.type="text/javascript";c.src=q;r(c,a)},loadCSS:function(q,a){const c=document.createElement("LINK");c.type="text/css";c.rel="stylesheet";c.href=q;r(c,a)},geoLocate:function(q){navigator.geolocation&&($(function(){PrimeFaces.cw("Growl","growl",{id:"growl",widgetVar:"growl",msgs:[{summary:"GeoLocating",detail:"Please wait...",severity:"info"}]})}),navigator.geolocation.getCurrentPosition(function(a){$(function(){PrimeFaces.cw("Growl","growl",{id:"growl",
widgetVar:"growl",msgs:[{summary:"GeoLocating",detail:"Done",severity:"info"}]})});q(`POINT (${a.coords.longitude} ${a.coords.latitude})`)},function(a){$(function(){PrimeFaces.cw("Growl","growl",{id:"growl",widgetVar:"growl",msgs:[{summary:"GeoLocating",detail:a.message,severity:"warn"}]})})},{enableHighAccuracy:!0}))},setTouchCookie:function(){let q=!1;if("maxTouchPoints"in navigator)q=navigator.maxTouchPoints>0;else if("msMaxTouchPoints"in navigator)q=navigator.msMaxTouchPoints>0;else{const a=window.matchMedia&&
matchMedia("(pointer:coarse)");a&&a.media==="(pointer:coarse)"?q=!!a.matches:"orientation"in window&&(q=!0)}document.cookie=`touch=${q?1:0}; path=/`},passwordStrength:{0:"Worst",1:"Bad",2:"Weak",3:"Good",4:"Strong"},progressBarPower:{0:"1%",1:"25%",2:"50%",3:"75%",4:"100%"},progressBarColour:{0:"#D73F40",1:"#DC6551",2:"#F2B84F",3:"#BDE952",4:"#3ba62f"}}}();
SKYVE.GMap=function(){let r=null;const q=function(a){switch(a){case "point":a=[google.maps.drawing.OverlayType.MARKER];break;case "line":a=[google.maps.drawing.OverlayType.POLYLINE];break;case "polygon":a=[google.maps.drawing.OverlayType.POLYGON,google.maps.drawing.OverlayType.RECTANGLE];break;case "pointAndLine":a=[google.maps.drawing.OverlayType.MARKER,google.maps.drawing.OverlayType.POLYLINE];break;case "pointAndPolygon":a=[google.maps.drawing.OverlayType.MARKER,google.maps.drawing.OverlayType.POLYGON,
google.maps.drawing.OverlayType.RECTANGLE];break;case "lineAndPolygon":a=[google.maps.drawing.OverlayType.POLYLINE,google.maps.drawing.OverlayType.POLYGON,google.maps.drawing.OverlayType.RECTANGLE];break;default:a=[google.maps.drawing.OverlayType.MARKER,google.maps.drawing.OverlayType.POLYLINE,google.maps.drawing.OverlayType.POLYGON,google.maps.drawing.OverlayType.RECTANGLE]}return a};return{scatter:function(a,c,b,d){r||=new Wkt.Wkt;var e=c.items;if(e){if(d)for(var g in a._objects){if(Object.prototype.hasOwnProperty.call(a._objects,
g)){var f=!1;for(let l=0,m=e.length;l<m;l++)if(e[l].bizId===g){f=!0;break}if(!f){f=a._objects[g];for(let l=0,m=f.overlays.length;l<m;l++)f.overlays[l].setMap(null),f.overlays[l]=null;delete f.overlays;delete a._objects[g]}}}else for(f in a._objects)if(Object.prototype.hasOwnProperty.call(a._objects,f)){g=a._objects[f];for(let l=0,m=g.overlays.length;l<m;l++)g.overlays[l].setMap(null),g.overlays[l]=null;delete g.overlays;delete a._objects[f]}for(let l=0,m=e.length;l<m;l++){g=e[l];if(f=a._objects[g.bizId]){if(d=
f.overlays.length===g.features.length)for(let n=0,p=f.overlays.length;n<p;n++)if(f.overlays[n].geometry!==g.features[n].geometry){d=!1;break}if(!d){for(let n=0,p=f.overlays.length;n<p;n++)f.overlays[n].setMap(null),f.overlays[n]=null;delete f.overlays;delete a._objects[bizId];f=null}}if(!f){f={overlays:[]};for(let n=0,p=g.features.length;n<p;n++){d=g.features[n];try{r.read(d.geometry)}catch(t){alert(`${d.geometry} is invalid WKT.`);continue}var h={editable:d.editable};d.strokeColour&&(h.strokeColor=
d.strokeColour);d.fillColour&&(h.fillColor=d.fillColour);d.fillOpacity&&(h.fillOpacity=d.fillOpacity);d.iconRelativeFilePath&&(h.icon={url:`${SKYVE.Util.CONTEXT_URL}resources?_n=${d.iconRelativeFilePath}&_doc=${c._doc}`},d.iconAnchorX&&d.iconAnchorY&&(h.icon.anchor=new google.maps.Point(d.iconAnchorX,d.iconAnchorY),h.icon.origin=new google.maps.Point(0,0)));h=r.toObject(h);f.overlays.push(h);h.setMap(a.webmap);d.zoomable&&(h.bizId=g.bizId,h.geometry=d.geometry,h.fromTimestamp=g.fromTimestamp,h.toTimestamp=
g.toTimestamp,h.mod=g.moduleName,h.doc=g.documentName,h.infoMarkup=g.infoMarkup,google.maps.event.addListener(h,"click",function(t){a.click(this,t)}))}a._objects[g.bizId]=f}}if(b){c=new google.maps.LatLngBounds;b=!1;for(const l in a._objects)if(Object.prototype.hasOwnProperty.call(a._objects,l)){b=!0;e=a._objects[l].overlays;for(let m=0,n=e.length;m<n;m++)if(g=e[m],g.getPath){g=g.getPath();for(let p=0,t=g.getLength();p<t;p++)c.extend(g.getAt(p))}else g.getPosition&&c.extend(g.getPosition())}b&&(c.getNorthEast().equals(c.getSouthWest())?
(a.webmap.getZoom()<15&&a.webmap.setZoom(15),overlay.getPosition!==void 0&&typeof overlay.getPosition==="function"&&a.webmap.setCenter(c.getNorthEast())):a.webmap.fitBounds(c))}}},centre:function(){r||=new Wkt.Wkt;let a=null;if(SKYVE.Util.mapCentre)try{r.read(SKYVE.Util.mapCentre);const c=r.components[0];a=new google.maps.LatLng(c.y,c.x)}catch(c){console.log(`${SKYVE.Util.mapCentre} is malformed WKT Point format`),SKYVE.Util.mapCentre=null,a=new google.maps.LatLng(0,0)}else a=new google.maps.LatLng(0,
0);return a},scatterValue:function(a,c){r||=new Wkt.Wkt;if(c){try{r.read(c)}catch(d){if(d.name==="WKTError"){alert("The WKT string is invalid.");return}}c=r.toObject(a.webmap.defaults);r.type!=="polygon"&&r.type!=="linestring"&&c.setEditable&&c.setEditable(!1);if(Wkt.isArray(c))for(var b in c)Object.prototype.hasOwnProperty.call(c,b)&&!Wkt.isArray(c[b])&&(c[b].setMap(a.webmap),a._overlays.push(c[b]));else c.setMap(a.webmap),a._overlays.push(c);if(c.getBounds!==void 0&&typeof c.getBounds==="function")a.webmap.fitBounds(c.getBounds());
else if(c.getPath!==void 0&&typeof c.getPath==="function"){b=new google.maps.LatLngBounds;c=c.getPath();for(let d=0,e=c.getLength();d<e;d++)b.extend(c.getAt(d));a.webmap.fitBounds(b)}else a.webmap.getZoom()<15&&a.webmap.setZoom(15),c.getPosition!==void 0&&typeof c.getPosition==="function"&&a.webmap.setCenter(c.getPosition())}},clear:function(a){for(let c=0,b=a._overlays.length;c<b;c++)a._overlays[c].setMap(null);a._overlays.length=0},drawingTools:function(a){r||=new Wkt.Wkt;a.webmap.drawingManager=
new google.maps.drawing.DrawingManager({drawingControlOptions:{position:google.maps.ControlPosition.LEFT_BOTTOM,drawingModes:q(a.drawingTools)}});a.webmap.drawingManager.setMap(a.webmap);google.maps.event.addListener(a.webmap.drawingManager,"overlaycomplete",function(c){SKYVE.GMap.clear(a);this.setDrawingMode(null);a._overlays.push(c.overlay);r.fromObject(c.overlay);c=r.write();a.setFieldValue(c)})},geoLocator:function(a){if(navigator.geolocation){const c=document.createElement("DIV");Object.assign(c.style,
{backgroundColor:"#fff",border:"2px solid #fff",borderRadius:"3px",boxShadow:"0 2px 6px rgba(0,0,0,.3)",cursor:"pointer",margin:"10px",padding:"5px",textAlign:"center"});c.title="Click to set your current position from your GPS";c.innerHTML='<i class="fa-solid fa-location-crosshairs"></i>';c.index=1;c.addEventListener("click",function(){navigator.geolocation.getCurrentPosition(function(b){SKYVE.GMap.clear(a);a.webmap.drawingManager.setDrawingMode(null);b={lat:b.coords.latitude,lng:b.coords.longitude};
const d=new google.maps.Marker({position:b,map:a.webmap});a._overlays.push(d);a.setFieldValue(`POINT (${b.lng} ${b.lat})`);a.webmap.setZoom(15);a.webmap.setCenter(b)},function(b){alert(b.message)},{enableHighAccuracy:!0})});a.webmap.geolocator=c;a.webmap.controls[google.maps.ControlPosition.LEFT].push(c)}},setDisabled:function(a,c){a.webmap&&(a.webmap.drawingManager&&a.webmap.drawingManager.setOptions({drawingControl:!c}),a.webmap.geolocator&&(a.webmap.geolocator.style.display=c?"none":"block"))},
refreshControls:function(a){const c=document.createElement("DIV");Object.assign(c.style,{backgroundColor:"#fff",border:"2px solid #fff",borderRadius:"3px",boxShadow:"0 2px 6px rgba(0,0,0,.3)",cursor:"pointer",margin:"10px",padding:"5px",textAlign:"center"});c.title="Click to set the refresh rate of the map";c.innerHTML=`
						        <input type="number" min="0" max="500" step="1" value="${a.refreshTime}" size="3" />
						        <input type="checkbox" ${a._refreshRequired?"checked":""}><label>Refresh</label>
						    `;c.index=1;c.children[0].addEventListener("change",function(){a.refreshTime=Number(this.value);a._refreshRequired&&(a._intervalId&&clearInterval(a._intervalId),a._intervalId=setInterval(a.rerender.bind(a),a.refreshTime*1E3))});c.children[1].addEventListener("click",function(){a._refreshRequired=this.checked;a._intervalId&&(clearInterval(a._intervalId),a._intervalId=null);a._refreshRequired&&(a.rerender(),a._intervalId=setInterval(a.rerender.bind(a),a.refreshTime*1E3))});a.webmap.controls[google.maps.ControlPosition.LEFT_BOTTOM].push(c)}}}();
SKYVE.Leaflet=function(){function r(b){function d(k){k=w.substring(x).match(k);if(!k)return null;x+=k[0].length;return k[0]}function e(){d(/^\s*/)}function g(){e();let k=0;const v=[],y=[v];let z=v,A;for(;A=d(/^(\()/)||d(/^(\))/)||d(/^(,)/)||d(c);){if(A==="(")y.push(z),z=[],y[y.length-1].push(z),k++;else if(A===")"){if(z.length===0)return null;z=y.pop();if(!z)return null;k--;if(k===0)break}else if(A===",")z=[],y[y.length-1].push(z);else{if(A.split(/\s/g).some(isNaN))return null;Array.prototype.push.apply(z,
A.split(/\s/g).map(parseFloat))}e()}return k!==0?null:v}function f(){const k=[];let v=[],y;for(;y=d(c)||d(/^(,)/);)y===","?(k.push(v),v=[]):y.split(/\s/g).some(isNaN)||(v||=[],Array.prototype.push.apply(v,y.split(/\s/g).map(parseFloat))),e();if(v)k.push(v);else return null;return k.length?k:null}function h(){if(!d(/^(point(\sz)?)/i))return null;e();if(!d(/^(\()/))return null;const k=f();if(!k)return null;e();return d(/^(\))/)?{type:"Point",coordinates:k[0]}:null}function l(){if(!d(/^(multipoint)/i))return null;
e();w=`MULTIPOINT (${w.substring(w.indexOf("(")+1,w.length-1).replace(/\(/g,"").replace(/\)/g,"")})`;const k=g();if(!k)return null;e();return{type:"MultiPoint",coordinates:k}}function m(){if(!d(/^(multilinestring)/i))return null;e();const k=g();if(!k)return null;e();return{type:"MultiLineString",coordinates:k}}function n(){if(!d(/^(linestring(\sz)?)/i))return null;e();if(!d(/^(\()/))return null;const k=f();return k&&d(/^(\))/)?{type:"LineString",coordinates:k}:null}function p(){const k=[];let v;if(!d(/^(geometrycollection)/i))return null;
e();if(!d(/^(\()/))return null;for(;v=t();)k.push(v),e(),d(/^(,)/),e();return d(/^(\))/)?{type:"GeometryCollection",geometries:k}:null}function t(){var k;(k=h()||n())||(d(/^(polygon(\sz)?)/i)?(e(),k=(k=g())?{type:"Polygon",coordinates:k}:null):k=null);(k=k||l()||m())||(d(/^(multipolygon)/i)?(e(),k=(k=g())?{type:"MultiPolygon",coordinates:k}:null):k=null);return k||p()}b=b.split(";");let w=b.pop();const u=(b.shift()||"").split("=").pop();let x=0;return function(k){k&&u.match(/\d+/)&&(k.crs={type:"name",
properties:{name:`urn:ogc:def:crs:EPSG::${u}`}});return k}(t())}function q(b){function d(h){return h.join(" ")}function e(h){return h.map(d).join(", ")}function g(h){return h.map(e).map(f).join(", ")}function f(h){return`(${h})`}b.type==="Feature"&&(b=b.geometry);switch(b.type){case "Point":return`POINT (${d(b.coordinates)})`;case "LineString":return`LINESTRING (${e(b.coordinates)})`;case "Polygon":return`POLYGON (${g(b.coordinates)})`;case "MultiPoint":return`MULTIPOINT (${e(b.coordinates)})`;case "MultiPolygon":return`MULTIPOLYGON (${b.coordinates.map(g).map(f).join(", ")})`;
case "MultiLineString":return`MULTILINESTRING (${g(b.coordinates)})`;case "GeometryCollection":return`GEOMETRYCOLLECTION (${b.geometries.map(q).join(", ")})`;default:throw Error("stringify requires a valid GeoJSON Feature or geometry object as input");}}const a=/[-+]?([0-9]*\.[0-9]+|[0-9]+)([eE][-+]?[0-9]+)?/,c=new RegExp("^"+a.source+"(\\s"+a.source+"){1,}");return{scatter:function(b,d,e,g){var f=d.items;if(f){if(g)for(var h in b._objects){if(Object.prototype.hasOwnProperty.call(b._objects,h)){var l=
!1;for(let m=0,n=f.length;m<n;m++)if(f[m].bizId===h){l=!0;break}if(!l){l=b._objects[h];for(let m=0,n=l.overlays.length;m<n;m++)b.webmap.removeLayer(l.overlays[m]),l.overlays[m]=null;delete l.overlays;delete b._objects[h]}}}else for(l in b._objects)if(Object.prototype.hasOwnProperty.call(b._objects,l)){h=b._objects[l];for(let m=0,n=h.overlays.length;m<n;m++)b.webmap.removeLayer(h.overlays[m]),h.overlays[m]=null;delete h.overlays;delete b._objects[l]}for(let m=0,n=f.length;m<n;m++){const p=f[m];if(h=
b._objects[p.bizId]){if(l=h.overlays.length===p.features.length)for(let t=0,w=h.overlays.length;t<w;t++)if(h.overlays[t].getLayers()[0].zoomData.geometry!==p.features[t].geometry){l=!1;break}if(!l){for(let t=0,w=h.overlays.length;t<w;t++)b.webmap.removeLayer(h.overlays[t]),h.overlays[t]=null;delete h.overlays;delete b._objects[p.bizId];h=null}}if(!h){h={overlays:[]};for(let t=0,w=p.features.length;t<w;t++){const u=p.features[t];l=r(u.geometry);l.properties={editable:u.editable};u.strokeColour&&(l.properties.color=
u.strokeColour);u.fillColour&&(l.properties.fillColor=u.fillColour);u.fillOpacity&&(l.properties.fillOpacity=u.fillOpacity);u.iconRelativeFilePath&&(g={iconUrl:`resources?_n=${u.iconRelativeFilePath}&_doc=${d._doc}`},u.iconAnchorX&&u.iconAnchorY&&(g.iconAnchor=[u.iconAnchorX,u.iconAnchorY]),l.properties.icon=g);l=L.geoJson(l,{pointToLayer(x,k){const v=x.properties;delete x.properties;v.icon&&(v.icon=L.icon(v.icon));return L.marker(k,v)},style:function(x){const k=x.geometry.properties;delete x.geometry.properties;
return k},onEachFeature:function(x,k){u.zoomable&&(k.zoomData={bizId:p.bizId,geometry:u.geometry,fromTimestamp:p.fromTimestamp,toTimestamp:p.toTimestamp,mod:p.moduleName,doc:p.documentName,infoMarkup:p.infoMarkup},k.bindPopup(function(v){return b.click(v)}))}});h.overlays.push(l);b.webmap.addLayer(l)}b._objects[p.bizId]=h}}if(e){d=L.latLngBounds();e=!1;for(const m in b._objects)if(Object.prototype.hasOwnProperty.call(b._objects,m)){e=!0;f=b._objects[m].overlays;for(let n=0,p=f.length;n<p;n++)d.extend(f[n].getBounds())}e&&
b.webmap.fitBounds(d,{maxZoom:15})}}},centre:function(){let b=[0,0];if(SKYVE.Util.mapCentre)try{const d=r(SKYVE.Util.mapCentre);b=[d.coordinates[1],d.coordinates[0]]}catch(d){console.log(`${SKYVE.Util.mapCentre} is malformed WKT Point format`),SKYVE.Util.mapCentre=null}return b},scatterValue:function(b,d){if(d){var e=null;try{e=L.geoJson(r(d))}catch(g){console.log(`The WKT string ${d} is invalid.`);return}e.addTo(b.webmap);b._overlays.push(e);b.webmap.fitBounds(e.getBounds(),{maxZoom:15})}},clear:function(b){for(let d=
0,e=b._overlays.length;d<e;d++)b.webmap.removeLayer(b._overlays[d]);b._overlays.length=0},drawingTools:function(b){const d=b.drawingTools;L.EditControl=L.Control.extend({options:{position:"topright"},onAdd:function(e){const g=L.DomUtil.create("div","leaflet-control leaflet-bar");if(!d||d==="point"||d==="pointAndLine"||d==="pointAndPolygon"){var f=L.DomUtil.create("a","",g);f.href="#";f.title="Create a new marker";f.innerHTML='<i class="fa-solid fa-location-dot"></i>';L.DomEvent.on(f,"click",L.DomEvent.stop).on(f,
"click",function(){window.LAYER=b.webmap.editTools.startMarker.call(e.editTools)},this)}d&&d!=="line"&&d!=="pointAndLine"&&d!=="lineAndPolygon"||(f=L.DomUtil.create("a","",g),f.href="#",f.title="Create a new line",f.innerHTML='<i class="fa-solid fa-diagram-project"></i>',L.DomEvent.on(f,"click",L.DomEvent.stop).on(f,"click",function(){window.LAYER=b.webmap.editTools.startPolyline.call(e.editTools)},this));d&&d!=="polygon"&&d!=="pointAndPolygon"&&d!=="lineAndPolygon"||(f=L.DomUtil.create("a","",g),
f.href="#",f.title="Create a new rectangle",f.innerHTML='<i class="fa-solid fa-vector-square"></i>',L.DomEvent.on(f,"click",L.DomEvent.stop).on(f,"click",function(){window.LAYER=b.webmap.editTools.startRectangle.call(e.editTools)},this),f=L.DomUtil.create("a","",g),f.href="#",f.title="Create a new polygon",f.innerHTML='<i class="fa-solid fa-draw-polygon"></i>',L.DomEvent.on(f,"click",L.DomEvent.stop).on(f,"click",function(){window.LAYER=b.webmap.editTools.startPolygon.call(e.editTools)},this));return g}});
b.webmap.editControl=new L.EditControl;b.webmap.addControl(b.webmap.editControl);b.webmap.on("editable:drawing:commit",function(e){SKYVE.Leaflet.clear(b);e.layer.toggleEdit();b._overlays.push(e.layer);b.setFieldValue(q(e.layer.toGeoJSON(12)))})},geoLocator:function(b){navigator.geolocation&&(L.GeoControl=L.Control.extend({options:{position:"bottomleft"},onAdd:function(d){d=L.DomUtil.create("div","leaflet-control leaflet-bar");const e=L.DomUtil.create("a","",d);e.href="#";e.title="Click to set your current position from your GPS";
e.innerHTML='<i class="fa-solid fa-location-crosshairs"></i>';L.DomEvent.on(e,"click",L.DomEvent.stop).on(e,"click",function(){b.webmap.editTools.drawing()&&b.webmap.editTools.commitDrawing();navigator.geolocation.getCurrentPosition(function(g){SKYVE.Leaflet.clear(b);const f=[g.coords.latitude,g.coords.longitude],h=L.marker(f);h.addTo(b.webmap);b._overlays.push(h);b.setFieldValue(`POINT (${g.coords.longitude} ${g.coords.latitude})`);b.webmap.setZoom(15);b.webmap.panTo(f)},function(g){alert(g.message)},
{enableHighAccuracy:!0})},this);return d}}),b.webmap.geoControl=new L.GeoControl,b.webmap.addControl(b.webmap.geoControl))},setDisabled:function(b,d){b.webmap&&(b.webmap.editControl&&(b.webmap.editControl.getContainer().style.display=d?"none":"block"),b.webmap.geoControl&&(b.webmap.geoControl.getContainer().style.display=d?"none":"block"))},refreshControls:function(b){L.GeoControl=L.Control.extend({options:{position:"bottomleft"},onAdd:function(d){d=L.DomUtil.create("div","leaflet-control");d.innerHTML=
`
		                <input type="number" min="0" max="500" step="1" value="${b.refreshTime}" size="3" />
		                <input type="checkbox" ${b._refreshRequired?"checked":""}><label>Refresh</label>
		            `;d.children[0].addEventListener("change",function(){b.refreshTime=Number(this.value);b._refreshRequired&&(b._intervalId&&clearInterval(b._intervalId),b._intervalId=setInterval(b.rerender.bind(b),b.refreshTime*1E3))});d.children[1].addEventListener("click",function(){b._refreshRequired=this.checked;b._intervalId&&(clearInterval(b._intervalId),b._intervalId=null);b._refreshRequired&&(b.rerender(),b._intervalId=setInterval(b.rerender.bind(b),b.refreshTime*1E3))});return d}});b.webmap.addControl(new L.GeoControl)}}}();SKYVE.PF=function(){var r=!1,q=function(){var a=sessionStorage.sessionHistory;return a=a?JSON.parse(a):[]};return{getById:function(a){return $(PrimeFaces.escapeClientId(a))},getByIdEndsWith:function(a){return $('[id$="'+a+'"]')},contentOverlayOnShow:function(a,c){SKYVE.PF.getById(a+"_overlayiframe").attr("src",c)},contentOverlayOnHide:function(a){SKYVE.PF.getById(a+"_overlayiframe").attr("src","")},afterContentUpload:function(a,c,b,d){top.$('[id$="_'+a+'_hidden"]').val(c);c="content?_n="+c+"&_doc="+
b+"&_b="+a.replace(/_/g,".");top.$('[id$="_'+a+'_link"]').attr("href",c).text(d).attr("onclick","return true");top.$('[id$="_'+a+'_image"]').attr("src",c);top.PF(a+"Overlay").hide()},clearContentImage:function(a){$('[id$="_'+a+'_hidden"]').val("");$('[id$="_'+a+'_image"]').attr("src","images/blank.gif")},clearContentLink:function(a){$('[id$="_'+a+'_hidden"]').val("");$('[id$="_'+a+'_link"]').attr("href","javascript:void(0)").text("<Empty>").attr("onclick","return false")},contentMarkupOnShow:function(a,
c,b){c=b+("&_id="+$('[id$="_'+c+'_hidden"]').val());SKYVE.PF.getById(a+"_markupiframe").attr("src",c)},contentMarkupOnHide:function(a){SKYVE.PF.getById(a+"_markupiframe").attr("src","")},afterMarkupApply:function(a,c,b,d){top.$('[id$="_'+a+'_hidden"]').val(c);c="content?_n="+c+"&_doc="+b+"&_b="+a.replace(/_/g,".");top.$('[id$="_'+a+'_link"]').attr("href",c).text(d).attr("onclick","return true");top.$('[id$="_'+a+'_image"]').attr("src",c);top.PF(a+"Markup").hide()},tabChange:function(a,c,b,d){sessionStorage["tab_"+
a+"_"+c+"_"+b]=d;SKYVE.BizMap&&SKYVE.BizMap.resizeAll();SKYVE.BizMapPicker&&SKYVE.BizMapPicker.resizeAll()},getTextElement:function(a){return SKYVE.PF.getById(a)},getTextValue:function(a){return SKYVE.PF.getTextElement(a).val()},setTextValue:function(a,c){SKYVE.PF.getTextElement(a).val(c)},getPasswordElement:function(a){return SKYVE.PF.getById(a+"password")},getPasswordValue:function(a){return SKYVE.PF.getPasswordElement(a).val()},setPasswordValue:function(a,c){SKYVE.PF.getPasswordElement(a).val(c)},
getComboElement:function(a){return SKYVE.PF.getById(a)},getLookupElement:function(a){return SKYVE.PF.getById(a)},getLookupValue:function(a){return SKYVE.PF.getById(a+"_hinput").val()},setLookupValue:function(a,c){SKYVE.PF.getById(a+"_hinput").val(c)},getLookupDescription:function(a){return SKYVE.PF.getById(a+"_input").val()},setLookupDescription:function(a,c){SKYVE.PF.getById(a+"_input").val(c)},getCheckboxElement:function(a){return SKYVE.PF.getById(a)},getCheckboxValue:function(a){var c=SKYVE.PF.getById(a+
"_input").val();return c=="0"?null:c=="1"?!0:c=="2"?!1:SKYVE.PF.getById(a+"_input").is(":checked")},setCheckboxValue:function(a,c){SKYVE.PF.getById(a+"_input").prop("checked",c);a=SKYVE.PF.getById(a).find(".ui-chkbox-box");var b=a.find(".ui-chkbox-icon");c?(a.addClass("ui-state-active"),b.addClass("ui-icon ui-icon-check")):(a.removeClass("ui-state-active"),b.removeClass("ui-icon ui-icon-check"))},establishHistory:function(){var a=q();if(a.length==0){var c=window.location.href;if(c.match(/.*[\?|&]a=e.*/)||
c.match(/.*[\?|&]a=e&.*/)){var b=document.referrer;b&&b!=""&&b!=c||(b=SKYVE.Util.CONTEXT_URL);a.push(b);sessionStorage.sessionHistory=JSON.stringify(a)}}},startHistory:function(a){sessionStorage.sessionHistory="[]";window.location.assign(a)},pushHistory:function(a){var c=q();c.push(window.location.href);sessionStorage.sessionHistory=JSON.stringify(c);a&&window.location.assign(a)},popHistory:function(a){var c=q();if(c.length>0){var b=c.pop();sessionStorage.sessionHistory=JSON.stringify(c);a&&window.location.assign(b)}},
saveHistory:function(a,c,b){for(var d=q(),e=!1,g=0;g<d.length;g++){for(var f=d[g],h=f.split(/\?|&/),l="m="+a,m="d="+c,n=!1,p=!1,t=!1,w=!1,u=0;u<h.length;u++){var x=h[u];x=="a=e"?n=!0:x==l?p=!0:x==m?t=!0:x.startsWith("i=")&&(w=!0)}n&&p&&t&&w&&(f+="&i="+b,d[g]=f,e=!0)}e&&(sessionStorage.sessionHistory=JSON.stringify(d));window.history&&history.replaceState&&(f=window.location.href+"&i="+b,history.replaceState({},"",f))},toggleFilters:function(a){a=$('[id$="'+a+'"]');if(a!=null){var c=function(){var b=
$(this);b.hasClass("hiddenFilter")?b.removeClass("hiddenFilter"):b.addClass("hiddenFilter")};a.find(".ui-filter-column").each(c);a.find(".ui-column-customfilter").each(c)}},onPushMessage:function(a){for(var c=[],b=0,d=a.length;b<d;b++){var e=a[b];if(e.type=="g")c.push({severity:e.severity,summary:e.message});else if(e.type=="m")PrimeFaces.showMessageInDialog({severity:e.severity,summary:"",detail:e.message,escape:!1});else if(e.type=="r")pushRerender();else if(e.type=="j")window[e.method](e.argument)}c.length>
0&&PrimeFaces.cw("Growl","pushGrowl",{id:"pushGrowl",widgetVar:"pushGrowl",life:6E3,sticky:!1,msgs:c})},gmap:function(a){if(r)setTimeout(function(){SKYVE.PF.gmap(a)},100);else{if(window.google&&window.google.maps&&window.SKYVE.BizMapPicker)return a.queryName||a.modelName?SKYVE.BizMap.create(a):SKYVE.BizMapPicker.create(a);r=!0;SKYVE.Util.loadJS("wicket/wicket.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("wicket/wicket-gmap3.js?v="+SKYVE.Util.v,function(){var c="https://maps.googleapis.com/maps/api/js?v=3&libraries=drawing";
SKYVE.Util.googleMapsV3ApiKey&&(c+="&key="+SKYVE.Util.googleMapsV3ApiKey);SKYVE.Util.loadJS(c,function(){SKYVE.Util.loadJS("skyve/prime/skyve-gmap-min.js?v="+SKYVE.Util.v,function(){r=!1;return a.queryName||a.modelName?SKYVE.BizMap.create(a):SKYVE.BizMapPicker.create(a)})})})})}},leaflet:function(a){if(r)setTimeout(function(){SKYVE.PF.leaflet(a)},100);else{if(window.L&&window.SKYVE.BizMapPicker)return a.queryName||a.modelName?SKYVE.BizMap.create(a):SKYVE.BizMapPicker.create(a);r=!0;SKYVE.Util.loadCSS("leaflet/leaflet.css?v="+
SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/leaflet.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/Path.Drag.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/Leaflet.Editable.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadCSS("leaflet/leaflet.fullscreen.css?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("leaflet/Leaflet.fullscreen.min.js?v="+SKYVE.Util.v,function(){SKYVE.Util.loadJS("skyve/prime/skyve-leaflet-min.js?v="+SKYVE.Util.v,function(){r=!1;return a.queryName||a.modelName?
SKYVE.BizMap.create(a):SKYVE.BizMapPicker.create(a)})})})})})})})}},chartExtender:function(){this.cfg.config.options||(this.cfg.config.options={});this.cfg.config.options.responsive=!0;this.cfg.config.options.maintainAspectRatio=!1},sidebar:function(a,c,b,d,e){$(function(){var g=$(window),f=$("head");$("body");var h=$("#"+a);h.children(".inner");$("#sidebarStyle"+e).length==0&&$('<style id="sidebarStyle'+e+'">.sidebar'+e+"{background-color:white;font-size:0.9em;position:relative;width:"+c+";flex-grow:0;flex-shrink:0;transition:margin-right 0.5s ease,box-shadow 0.5s ease;}.sidebar"+
e+" .toggle{text-decoration:none;transition:right 0.5s ease;-webkit-tap-highlight-color:rgba(255,255,255,0);border:0;display:none;position:absolute;top:calc(50% - 3.75em);right:calc("+d+"px - 3em);width:4em;height:7.5em;line-height:6.25em;text-align:center;z-index:10000;}.sidebar"+e+" .toggle:before{font-family:FontAwesome;font-size:1.1rem;font-style:normal;font-weight:normal;text-transform:none !important;content:'>';height:inherit;right:0;line-height:inherit;position:absolute;text-indent:0;top:0;width:inherit;color:#7f888f;margin-right:1.5em;margin-top:-0.5em;z-index:1;}.sidebar"+
e+" .toggle:after{background:rgba(222,225,226,0.75);border-radius:0.375em;content:'';height:3em;right:2em;position:absolute;top:1em;width:3em;}.sidebar"+e+".inactive{margin-right:-"+d+"px;}.sidebar"+e+".inactive .toggle:before{content:'<';}@media screen and (max-width:"+b+"px){.sidebar"+e+"{box-shadow:0 0 5em 0 rgba(0,0,0,0.175);position:fixed;top:0;right:0;width:"+d+"px;height:100%;z-index:10000;}.sidebar"+e+".inactive{box-shadow:none;}.sidebar"+e+">.inner{position:absolute;top:0;right:0;width:100%;height:100%;overflow-x:hidden;overflow-y:auto;-webkit-overflow-scrolling:touch;}.sidebar"+
e+" .toggle{display:flex;}}</style>").appendTo(f);g.on("resize",function(){g.width()<=b?h.addClass("inactive"):h.removeClass("inactive")});g.trigger("resize");$('<a href="#'+a+'" class="toggle"></a>').appendTo(h).on("click",function(l){l.preventDefault();l.stopPropagation();h.toggleClass("inactive")});window.setTimeout(function(){h.show()},100)})}}}();
//# sourceMappingURL=skyve-min.js.map