name: Sonar Analysis

on:
  workflow_dispatch:
  schedule:
    # Run at 1pm UTC every Sunday, around 10-11pm Adelaide time
    - cron: '0 13 * * 0'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 0  # Disable shallow clone for better analysis
    - name: Set up JDK 17
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: >-
        mvn -B -Pcoverage -pl skyve-coverage -am
        -DskipIntegrationTests=true -DskipUnitTests=false
        verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
    - name: Test Report
      uses: dorny/test-reporter@df6247429542221bc30d46a036ee47af1102c451 # v2
      if: success() || failure()
      with:
        name: Test Report
        path: '**/target/surefire-reports/TEST-*.xml'
        reporter: java-junit